### ISSUE TITLE
ytdl:// The protocol is either unsupported, or was disabled at compile-time.

### ISSUE THREAD

**Issue by kslr** [mpv-player/mpv-build#100]
I use rebuild script.
Whether need other instructions to open

**Comment by sfan5** [comment]
You need Lua installed for youtube-dl support. Does the OSC work?
If you're on a Debian-like distro try installing `liblua5.2-dev`

**Comment by kslr** [comment]
i use ubuntu 16.04
apt install liblua5.2-dev ok;
youtube-dl ok;
osc ok;
lua 5.3 ok;

**Comment by sfan5** [comment]
If you have installed Lua, you need to run `./rebuild` for the changes to take effect.

**Comment by Argon-** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#Why_does_mpv_not_support_Lua_53

**Comment by kslr** [comment]
I installed Lua can work, thank you everyone.
