### ISSUE TITLE
Configuration to build mpv with static link on Windows

### ISSUE THREAD

**Issue by tellamon** [mpv-player/mpv-build#104]
I'm fine with building mpv.exe with the help of mpv-build scripts with use-*-master in msys64 environment on Windows 10.
But it shows error message that it could not find dlls like libwinpthread-1.dll when I execute mpv.exe. I know I can run mpv.exe with all those dlls in \mingw64\bin folder but it's somewhat inconvenient to deploy them all.

I figured out that the binaries from https://sourceforge.net/projects/mpv-player-windows/files/ are fine to run alone without dlls since they must be statically linked with the libraries.

Is there any configuration support from mpv-build to make mpv.exe which is running fine standalone on Windows10?

**Comment by kevmitch** [comment]
I have in the past used mpv-build with mxe from linux to produce a fully self contained windows binary. It is currently out of scope do this in msys2, which is complicated enough trying to produce a shared executable. If you really want to reproduce the shinchiro build you could use [the build scripts](https://github.com/shinchiro/mpv-winbuild-cmake), which are a fork of [lachs0r's](https://github.com/lachs0r/mingw-w64-cmake) used to produce the release binaries

**Comment by tellamon** [comment]
Thanks, @kevmitch. I'll give it a try.
