### ISSUE TITLE
If cuda/cuvid/nvdec is requested, ffnvcodec should be built

### ISSUE THREAD

**Issue by jesusdf** [mpv-player/mpv-build#105]
Apparently, ffmpeg support for cuda was moved to a separate repository, it should be downloaded and built if cuda/cuvid/nvdec is requested.

http://ffmpeg.org/pipermail/ffmpeg-devel/2018-March/226039.html

https://superuser.com/questions/1299064/error-cuvid-requested-but-not-all-dependencies-are-satisfied-cuda-ffnvcodec

```
git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
cd nv-codec-headers
make && sudo make install
```

This worked for me before running the rebuild script.

**Comment by wm4** [comment]
We don't do such things (auto downloading deps) in the proper mpv repo.

**Comment by wm4** [comment]
Nevermind, this _is_ the mpv-build repo. Makes sense then, if someone wants to implement it.

**Comment by wm4** [comment]
I think by now most distros have packages for this.
