### ISSUE TITLE
MacOS Build Issue

### ISSUE THREAD

**Issue by Ahmedbutt** [mpv-player/mpv-build#108]
I am tryting to build mpv using mpv script but having following issue:

<img width="978" alt="screen shot 2018-06-08 at 5 16 23 am" src="https://user-images.githubusercontent.com/5628406/41132519-1f38120c-6adb-11e8-8463-fe15b0848132.png">

Can you please tell me what is the issue?

**Comment by wm4** [comment]
Use homebrew.
