### ISSUE TITLE
Build libmpv

### ISSUE THREAD

**Issue by shengyang998** [mpv-player/mpv-build#111]
Maybe the document should note that if one want to build a dynamic mpv (libmpv), one should not only put `--enable-libmpv-shared` in file `mpv_options` but also put `--enable-shared` in file `ffmpeg_options`. Furthermore one need to change `--disable-shared` to `--enable-shared` at the end of the file `scripts/libass-config`. 

Otherwise, an Error like below may occured
```shell
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _sub_recode in libass.a(ass.o)
     (maybe you meant: _mp_iconv_to_utf8)
  "_iconv_close", referenced from:
      _sub_recode in libass.a(ass.o)
  "_iconv_open", referenced from:
      _sub_recode in libass.a(ass.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wm4** [comment]
One can definitely build a libmpv with static ffmpeg and libass in theory, just needs to enable PIC. Out of scope I'd say.
