### ISSUE TITLE
Build faiure

### ISSUE THREAD

**Issue by khallebal** [mpv-player/mpv-build#112]
How do i fix this build? i am not very familiar with ./waf , so i can't really see why it's fallling.
thank you.
ps: This is on haiku 32 bit using gcc-7.3.0

> 
>  -> task in 'mpv' failed (exit status 1): 
>         {task 9328364: c af_lavcac3enc.c -> af_lavcac3enc.c.12.o}
> ['/boot/system/bin/x86/gcc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-I/boot/home/Desktop/bomi-0.9.11/src/mpv/build', '-I/boot/home/Desktop/bomi-0.9.11/src/mpv', '-I/packages/libdvdnav_x86-6.0.0-1/.self/develop/headers/x86', '-I/packages/libdvdread_x86-6.0.0-2/.self/develop/headers/x86', '-I/packages/ffmpeg_x86-4.0.2-1/.self/develop/headers/x86', '-I/packages/libcdio_paranoia_x86-10.2_0.94_2-1/.self/develop/headers/x86', '-I/packages/libcdio0_x86-0.94-1/.self/develop/headers/x86', '-I/packages/libbluray_x86-1.0.2-1/.self/develop/headers/x86', '-I/packages/libxml2_x86-2.9.3-5/.self/develop/headers/x86/libxml2', '-I/packages/freetype_x86-2.9-1/.self/develop/headers/x86/freetype2', '-I/packages/fontconfig_x86-2.12.6-2/.self/develop/headers/x86', '-I/packages/fontconfig_x86_devel-2.12.6-2/devel~libfreetype_x86/develop/headers/x86/freetype2', '-I/packages/fontconfig_x86_devel-2.12.6-2/devel~libxml2_x86/develop/headers/x86/libxml2', '-I/packages/libsdl2_x86-2.0.8-3/.self/develop/headers/x86/SDL2', '-I/packages/libass_x86-0.14.0-2/.self/develop/headers/x86', '-I/packages/harfbuzz_x86-2.0.2-1/.self/develop/headers/x86/harfbuzz', '-I/packages/glib2_x86-2.57.1-1/.self/develop/headers/x86/glib-2.0', '-I/packages/glib2_x86-2.57.1-1/.self/develop/lib/x86/glib-2.0/include', '-I/packages/libpcre_x86-8.42-1/.self/develop/headers/x86', '-I/packages/graphite2_x86-1.3.10-1/.self/develop/headers/x86', '-I/packages/fribidi_x86-1.0.5-1/.self/develop/headers/x86/fribidi', '-DHAVE_DVDNAV=1', '-DHAVE_DVDREAD=1', '-DHAVE_LIBAV=1', '-DHAVE_CDDA=1', '-DHAVE_LIBSWRESAMPLE=1', '-DHAVE_LIBBLURAY=1', '-DHAVE_SDL2=1', '-D_REENTRANT', '-DHAVE_LIBASS=1', '../audio/filter/af_lavcac3enc.c', '-c', '-o', '/boot/home/Desktop/bomi-0.9.11/src/mpv/build/audio/filter/af_lavcac3enc.c.12.o']
>

**Comment by sfan5** [comment]
Your log does not include any of compiler output (error/warning messages).

**Comment by khallebal** [comment]
> Your log does not include any of compiler output (error/warning messages).

Yes, that's just the terminal output, sorry about that, i couldn't find the log because as i said, i am not familiar with the waf build system, that's why i submitted this issue.
So where can i find the relevant log file?

**Comment by sfan5** [comment]
waf usually logs to stdout, but since you're using `bomi`'s buildscript why don't you go and ask [them](https://github.com/xylosper/bomi)?

Their mpv is also 3 years out of date, no support for that.

**Comment by khallebal** [comment]
> waf usually logs to stdout, but since you're using `bomi`'s buildscript why don't you go and ask [them](https://github.com/xylosper/bomi)?
> 
> Their mpv is also 3 years out of date, no support for that.

Sorry @sfan5 , i didn't mean to be rude by submitting this issue here, but because it's mpv that was failling to build i thought i'd ask here, but you're right it's a bit offending.
FWIW, there is already a working mpv 0.29.0 for haiku, i was just trying to get a build for bomi.
