### ISSUE TITLE
error: Libtool library used but 'LIBTOOL' is undefined

### ISSUE THREAD

**Issue by thrisp** [mpv-player/mpv-build#116]
lubuntu 18.10, fresh install trying to build mpv

run
./build 

get: 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
libass/Makefile.am:25: error: Libtool library used but 'LIBTOOL' is undefined
libass/Makefile.am:25:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
libass/Makefile.am:25:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
libass/Makefile.am:25:   If 'LT_INIT' is in 'configure.ac', make sure
libass/Makefile.am:25:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

**Comment by lachs0r** [comment]
Install libtool.

**Comment by thrisp** [comment]
obvious in hindsight, thank you

**Comment by varenc** [comment]
thank you! Just ran into this while compiling mpv on a raspberry pi.  The error didn't make it super obvious, but it was still pretty obvious in retrospect..

```
Makefile.am:12: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:12:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:12:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:12:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:12:   its definition is in aclocal's search path.
```
