### ISSUE TITLE
mpv can't see  ffmpeg if mpv_options enable-static-build is selected

### ISSUE THREAD

**Issue by Xuno** [mpv-player/mpv-build#118]
Using msys2 to build mpv-1.dll with most dependent libs.
Used options:
```
ffmpeg_options                                                                                                                    
--enable-shared
--enable-static

mpv_options                                                                                                               
--enable-libmpv-shared
--enable-static-build
```

ffmpeg built ok
but mpv can't see  ffmpeg if mpv_options enable-static-build is selected 

Result of waf --configure
```
Checking for FFmpeg/Libav present                                    : yes
Checking for libav* is FFmpeg                                        : no
Checking for libav* is Libav                                         : no
Checking for Libav/FFmpeg library versions                           : ffmpeg not found
Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.
```

Many years ago manual builds using https://lexxai.blogspot.com/2016/02/mpv-player-static-os-windows-msys2.html were successful, but now fails.

**Comment by gy-lehel** [comment]
Hi
I ran into the same issue, here is the solution for using release both in ffmpeg and mpv.

https://github.com/mpv-player/mpv/issues/6838

**Comment by wm4** [comment]
Pending upstream changes, I guess. Closing because not directly related to the mpv-build scripts.
