### ISSUE TITLE
Can't build package on Ubuntu (issues with --enable-dvdread)

### ISSUE THREAD

**Issue by tsjnachos117** [mpv-player/mpv-build#120]
I've just spent the last few hours trying to figure out why dpkg-buildpackage was failing. The only output of any real note was this:

    waf: error: no such option: --enable-dvdread

I had `--enable-dvdread` in my mpv_options file, so I though "let's see what happens when I remove it". I did (and prayed like heck that DVDs would somehow still work), and ended up **WITH THE SAME ERROR**!

So after several hours of unsuccessfully trying to build this package, I found that the debian/rules file has this line of code (line 66):

    		--enable-dvdread \

IDK why waf chokes on this option, as it worked fine last time I built mpv. Is it somehow obsolete? Is this no longer supported? If so, I suggest you remove this line entirely. Otherwise, perhaps you should add support for this switch back into waf. (I don't care too much either way, as long as my DVDs still play, which still seems to be the case. :)

**Comment by Argon-** [comment]
https://github.com/mpv-player/mpv/commit/62294049852549e99ec948e0df16452856afa0c1
Was removed.

**Comment by wm4** [comment]
It's hardcoded: https://github.com/mpv-player/mpv-build/blob/master/debian/rules#L66
