### ISSUE TITLE
/usr/bin/env: python3: No such file or directory

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#124]

**Comment by mrkapqa** [comment]
Hello ,

i get this error on Debian Wheezy with latest mpv-build


git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
./update
...
...
+ git checkout origin/master
HEAD is now at 4083277... osc: more frequent cache updates: from 10% diff to 5% or 5s
+ git remote prune origin
+ do_update_debian_versions
+ scripts/debian-update-versions
+ do_bootstrap
+ scripts/mpv-bootstrap
/usr/bin/env: python3: No such file or directory

**Comment by sfan5** [comment]
You need to install `python3`. Your distro release is also EOL since 2018, go update.

**Comment by mrkapqa** [comment]
thanks, got this error when build

[143/207] Compiling video/out/opengl/egl_helpers.c
../video/out/opengl/egl_helpers.c: In function 'mpegl_get_display':
../video/out/opengl/egl_helpers.c:329:13: error: unknown type name 'EGLAttrib'
../video/out/opengl/egl_helpers.c: At top level:
cc1: warning: unrecognized command line option "-Wno-format-truncation" [enabled by default]

../input/cmd.c: In function 'mp_input_parse_cmd_str':
../input/cmd.c:454:13: warning: value computed is not used [-Wunused-value]
../input/cmd.c:467:9: warning: value computed is not used [-Wunused-value]
../input/cmd.c: In function 'mp_cmd_clone':
../input/cmd.c:532:13: warning: value computed is not used [-Wunused-value]
../input/cmd.c: At top level:
cc1: warning: unrecognized command line option "-Wno-format-truncation" [enabled by default]

**Comment by CounterPillow** [comment]
# UPDATE YOUR OPERATING SYSTEM JESUS CHRIST

**Comment by mrkapqa** [comment]
yeah, thanks, i am still on windows 7!

won't help to solve this issue, though :)

**Comment by Dudemanguy** [comment]
You need a semi-recent compiler to compile mpv. I don't know when exactly `Wno-format-truncation`was added but it had to be years ago. The best solution is really to just update your distro.

**Comment by mrkapqa** [comment]
Thanks ,

i think this change must have come in recently as i think it was still possible to build on wheezy in 2019 the latest mpv.
solved it by installing devuan jessie distro and mpv from deb-multimedia (version 0.8.3 only, but it seems fully functional for my need)

**Comment by mrkapqa** [comment]
if someone wants to try it on debian wheezy, this is the routine that helped me through last year if i remember correctly


sudo apt-get install git build-essential devscripts equivs
sudo aptitude install autoconf automake libasound2-dev libegl1-mesa-dev libfontconfig-dev libfreetype6-dev libfribidi-dev libgl1-mesa-dev libgnutls-dev libtool libx11-dev libxext-dev libxinerama-dev libxrandr-dev libxv-dev pkg-config python x11proto-core-dev yasm libxss-dev liblua5.2-dev libssl-dev

git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
./update
./clean
cd libass
git checkout 9a2b38e8f5957418362e86b525f72794565deedd
cd ..
echo --disable-drm >> mpv_options
./build -j2
sudo ./build install
