### ISSUE TITLE
(debian wheezy 64bit) cc1: warning: unrecognized command line option "-Wno-format-truncation" [enabled by default]

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#125]
Hello ,

i tried to build the latest mpv on Debian Wheezy 64bit and it would no longer build.:

the following error occured:

[ 92/207] Compiling video/out/opengl/egl_helpers.c
../video/out/opengl/egl_helpers.c: In function 'mpegl_get_display':
../video/out/opengl/egl_helpers.c:329:13: error: unknown type name 'EGLAttrib'
../video/out/opengl/egl_helpers.c: At top level:
cc1: warning: unrecognized command line option "-Wno-format-truncation" [enabled by default]

Please let me know if there is an option to overcome this error.

thank you very much,,

Richard

**Comment by wm4** [comment]
We're already testing whether a compiler accepts warning options. If the compiler is stupid enough to ignore unknown warnings (and only prints a warning not easily detectable by build scripts), it's the idiotic compiler dev's fault, not ours. (Seriously, what the fuck are these fucking idiots thinking?)

The actually interesting part about EGL means you need to update EGL or disable it.

**Comment by avih** [comment]
> We're already testing whether a compiler accepts warning options

We do as best as we (so far) can, but due to twisted semantics of when it fires and when suppressed, IIRC it's impossible to detect the support correctly, and iirc it ends suppressed if there are no other warnings, else it ends up firing these "unknown warning..." warnings.

**Comment by avih** [comment]
That's the commit which somewhat detects it correctly if anyone is interested in improving it: https://github.com/mpv-player/mpv/commit/4cda63bd14c2087eb372fbb282fb47aea77a7923

**Comment by CounterPillow** [comment]
Dude we've told you before to upgrade your EOL distro but you keep opening these garbage ass issues instead.

Do we really need to block you from the mpv org?

**Comment by mrkapqa** [comment]
hei, thanks,
i am using older hardware so it seems legit to ask for directions here ;
the issues have quite always been adressed and i could learn quite abit.
this issue has already been closed - so i don't know if it has been adressed or will be.
in any case - there seem no packages available for the legacy operating systems like ubuntu precise or debian squeeze.
it would be nice to have a repository to serve also the folks on the other end of the spectrum, or as you call them, those still using EOL products.
Feel free to block me, however, i would have to consider this a rather undemocratic move.
If i violated some rules, please let me know it.

**Comment by wm4** [comment]
mpv should have rejected your EGL libs. This should probably be fixed.

Other than that, we simply don't support old software environments if it causes the developers severe pain.
