### ISSUE TITLE
(debian jessie) libvpx enabled but no supported decoders found

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#126]
Hello ,

since the version of mpv in debian jessie is outdated and probably with error

resorted to this help here to install - build on my own 

https://nyxi.eu/compiling-mpv-on-debian.html

during compiling i get this error

libvpx enabled but no supported decoders found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

Thanks

**Comment by mrkapqa** [comment]
[mpv_2020.02.10.8c2179b_amd64.txt](https://github.com/mpv-player/mpv-build/files/4183449/mpv_2020.02.10.8c2179b_amd64.txt)

**Comment by CounterPillow** [comment]
This is ffmpeg's configure failing, not mpv. Seems like you enabled libvpx in `ffmpeg_options`, but didn't install libvpx. If you don't plan on using mpv for encoding, there's no point to enabling libvpx though, since FFmpeg's internal decoder is superior.

**Comment by mrkapqa** [comment]
according to apt-get libvpx1      libvpx-dev are installed.

**Comment by mrkapqa** [comment]
on another build (always devuan/debian jessie) the following occured


[ 92/218] Compiling misc/charset_conv.c
In file included from ../misc/charset_conv.c:32:0:
/usr/include/uchardet/uchardet.h:52:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
 uchardet_t uchardet_new();
 ^
cc1: warning: unrecognized command line option "-Wno-format-truncation"

[ 93/218] Compiling video/out/vo_x11.c
[ 94/218] Compiling video/out/dr_helper.c
[ 95/218] Compiling player/client.c
[ 96/218] Compiling input/cmd.c
[ 97/218] Compiling filters/user_filters.c
[ 98/218] Compiling video/out/opengl/egl_helpers.c
../video/out/opengl/egl_helpers.c: In function 'mpegl_get_display':
../video/out/opengl/egl_helpers.c:329:37: error: unknown type name 'EGLAttrib'
             (EGLenum, void *, const EGLAttrib *) =
                                     ^
../video/out/opengl/egl_helpers.c: At top level:
cc1: warning: unrecognized command line option "-Wno-format-truncation"

../player/client.c: In function 'cmd_complete':
../player/client.c:1038:9: warning: missing braces around initializer [-Wmissing-braces]
         cmd->result = (mpv_node){0};
         ^
../player/client.c:1038:9: warning: (near initialization for '(anonymous).u') [-Wmissing-braces]
../player/client.c: In function 'async_cmd_complete':
../player/client.c:1126:5: warning: missing braces around initializer [-Wmissing-braces]
     cmd->result = (mpv_node){0};
     ^
../player/client.c:1126:5: warning: (near initialization for '(anonymous).u') [-Wmissing-braces]
../player/client.c: At top level:
cc1: warning: unrecognized command line option "-Wno-format-truncation"

Waf: Leaving directory `/home/rich/Programme/mpv-build/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)

**Comment by lachs0r** [comment]
Debian Jessie is oldoldstable by now. This is too old to support.

**Comment by mrkapqa** [comment]
This procedure here helped to install an older version of mpv for Debian Jessie
https://github.com/mpv-player/mpv-build/issues/94
