### ISSUE TITLE
Build succeded but can't install

### ISSUE THREAD

**Issue by CBSkarmory** [mpv-player/mpv-build#128]
After running `./build` I get
```
Waf: Leaving directory `$HOME/inst/mpv/mpv-build/mpv/build'
'build' finished successfully (14.611s)
```
and a zero exit status (good).

It seems like the build really was successful, as I can run use the binary to play video files

However, when trying to install with `sudo ./install`:
```
The project was not configured: run "waf configure" first!
```
If I try to use `waf configure` (`cd mpv; ./waf configure`):
```
... (omitted) ...
Checking for Libav/FFmpeg library versions                                : no ('libavutil >= 56.12.100 libavcodec >= 58.16.100 libavformat >= 58.9.100 libswscale >= 5.0.101 libavfilter >= 7.14.100 libswresample >= 3.0.100' not found)
Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.
```
which seems weird since the binary really did build and I should have those requirements in ffmpeg (separate from mpv-build):
```
ffmpeg version n4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
configuration: --prefix= --prefix=/usr --disable-debug --disable-doc --disable-static --enable-avisynth --enable-cuda --enable-cuvid --enable-libdrm --enable-ffplay --enable-gnutls --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopus --enable-libpulse --enable-sdl2 --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-nonfree --enable-nvenc --enable-omx --enable-openal --enable-opencl --enable-runtime-cpudetect --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-xlib
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
```

Any advice on how to properly finish the build/install process? Just moving the binary and adding it to my path seems really hacky.

**Comment by CounterPillow** [comment]
Please post the full build log, from the time you type ./build.

**Comment by CBSkarmory** [comment]
build log:
https://pastebin.com/9M3p59vf
exit code 0

**Comment by CounterPillow** [comment]
Looks like it indeed built successfully. Since mpv-build builds a static binary, you can just symlink it to a /usr/local/bin or copy it there. I'm not sure what's up with the mpv-install script being broken. FWIW, the waf configure failing if you run it manually, but it succeeding if you use mpv-build, is because the mpv-build scripts set some paths to point towards the ffmpeg build it just made.

**Comment by Dudemanguy** [comment]
Waf support no longer exists and I will naively assume that meson's install command works.
