### ISSUE TITLE
segmentation-fault when skipping forward

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#137]
Hello,

i would like to know if can improve this build mpv.0.22 on powerpc64.

the graphics card is agp 7800gt and should be capable enough.

the sample-file plays, but upon skipping there is segmentation fault.

https://paste.ubuntu.com/p/CDr9ZsfG2N/

https://paste.ubuntu.com/p/NGJYG2t7pq/

**Comment by Akemi** [comment]
we don't give support for outdated versions. also this is the wrong issue tracker for mpv issues.
