### ISSUE TITLE
Building mpv with srt protocol support

### ISSUE THREAD

**Issue by maci3k90** [mpv-player/mpv-build#138]
Hello.

What I have already tried:
1. ./clean
2. Downloading latest libsrt from _https://github.com/Haivision/srt_
3. Install it to _build_libs_ directory in _mpv-build_ directory
4. Adding neccessary ffmpeg options to _ffmpeg_options_ file:

`--enable-libsrt
--extra-cflags="-I$BUILD/build_libs/include"
--extra-ldflags="-L$BUILD/build_libs/lib"`

5. ./build -j4

Process has ended successfully. Unfortunately for command:

`./mpv srt://localhost:8090`

mpv says:

`No protocol handler found to open URL srt://localhost:8090
The protocol is either unsupported, or was disabled at compile-time.`

Compiled ffmpeg binaries (including ffplay) works with srt.

What I have missed?

**Comment by wm4** [comment]
Prefix with `av://` (I think) to use ffmpeg's protocol matching.
