### ISSUE TITLE
configure: error: Package requirements (harfbuzz >= 1.2.3) were not met:

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#140]
hello ,

when trying to install mpv on ubuntu 20.04

the following error occurs

configure: error: Package requirements (harfbuzz >= 1.2.3) were not met:
No package 'harfbuzz' found

it used to functiong previously well;

thank you.

**Comment by CounterPillow** [comment]
Install libharfbuzz-dev, libass needs that, and mpv now refuses to build without libass unless you explicitly tell it not to AFAIK.

**Comment by mrkapqa** [comment]
thank you again, now it functions. all well.

**Comment by CounterPillow** [comment]
Then you should close the issue.
