### ISSUE TITLE
Can't build on Ubuntu w/dpkg-buildpackge: "run waf configure first"

### ISSUE THREAD

**Issue by tsjnachos117** [mpv-player/mpv-build#147]
I've tried just about everything I can think of, but I can't seem to build mpv through the dpkg-buildpackage frontend. Everytime I try, after it builds ffmpeg and seems to build mpv. However, it eventually gives me the fallowing error, presumably when it's supposed to start packaging: `The project was not configured: run "waf configure" first!`

I'm running Ubuntu 20.04, x86-64. I use the following arguments to dpkg-buildpackage: `-uc -us -b -j2`.

[Here is a log of my last attempt at building](https://pastebin.com/by5Kb1Y9) (copied/pasted from my terminal).

**Comment by sfan5** [comment]
The README says:

> Debian no longer provides an unversioned "python" binary on its own. You need to explicitly tell it to create a symlink to python3 if this is the case:
> ```
> which python || sudo apt-get install python-is-python3
> ```

This is super inconvenient however and I don't know why we don't just fix this in our scripts.

**Comment by sfan5** [comment]
There: abc1380522f81223d09c19f2ad378948f80a9e2b
