### ISSUE TITLE
Ubuntu 16.04 Xenial: requested 'harfbuzz >= 1.2.3' but version of harfbuzz is 1.0.1. Can't find a newer version for Xenial.

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv-build#153]
Can't find a way around this.
Is it no longer possible to build libass on Ubuntu LTS 16.04?

**Comment by avih** [comment]
>  Is it no longer possible to build libass on Ubuntu LTS 16.04?

Judging by your title, it appears so.

As a workaround, after you update libass, you can `cd` into its source directory and `git checkout` some older version which doesn't require this version of harfbuzz.

mpv-build does not build the entire dependency tree. For instance, if some future ffmpeg will need gcc >= 10.0 then mpv-build will assume you have that version of gcc, and will not build it. Same goes for harfbuzz.

**Comment by Paco8** [comment]
It can be fixed with `./use-libass-custom 0.14.0`
