### ISSUE TITLE
Error opening/initializing the selected video_out (--vo) device.

### ISSUE THREAD

**Issue by dbkblk** [mpv-player/mpv-build#156]
Hello,
I've used the build script before succesfully on Debian 11, but I've decided to switch recently to OpenSuse Tumbleweed, and since then, every build doesn't launch.

I've tried to build 0.32, 0.33, 0.33.1 and a combinaison of different ffmpeg versions. They all gave the same error.

The main opensuse mpv version works, but it crashes when seeking a new video position with svp4linux.
I had the same problem on Arch and Debian 11, but on Debian, I've managed to workaround this by building with this script. Now, this doesn't work anymore.

My GPU is a Nvidia GTX970 with the latest drivers (460 series). OpenCL and Vulkan are OK.

Do you have any idea why ?

Thank you.

```
hadrien@hfixe:~/Apps/builds/mpv-build> mpv -v test.mkv 
[cplayer] Command line options: '-v' 'test.mkv'
[cplayer] mpv 0.33.0-115-gf1d0365a6f Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Apr  9 20:46:32 CEST 2021
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.72.100
[cplayer]    libavcodec      58.135.100
[cplayer]    libavformat     58.78.100
[cplayer]    libswscale      5.10.100
[cplayer]    libavfilter     7.111.100
[cplayer]    libswresample   3.10.100
[cplayer] FFmpeg version: N-101901-gb593abda6c
[cplayer] 
[cplayer] Configuration: ./waf configure --enable-libmpv-shared
[cplayer] List of enabled features: alsa asm build-date caca cplayer cplugins debug-build egl egl-helpers ffmpeg gl glibc-thread-name glob glob-posix gpl iconv libass libavdevice libdl libm libmpv-shared librt linux-fstatfs linux-input-event-codes optimize plain-gl posix posix-or-mingw pthreads pulse stdatomic vapoursynth vt.h zimg zlib
[cplayer] Reading config file /usr/local/etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/hadrien/.config/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'input-ipc-server' = '/tmp/mpvsocket' (flags = 4)
[cplayer] Setting option 'hr-seek-framedrop' = 'no' (flags = 4)
[cplayer] Setting option 'af' = 'lavfi=[acompressor=level_in=0.4:attack=30:release=300:threshold=-20dB:ratio=20:makeup=15dB]' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[ipc] Starting IPC master
[ipc] Listening to IPC socket.
[file] Opening test.mkv
[demux] Trying demuxers for level=normal.
[mkv] Seeking to 2122806162 to read header element 0x1c53bb6b.
[file] stream level seek from 131072 to 2122806162
[mkv] Parsing cues...
[mkv] Seeking to 2122886816 to read header element 0x1254c367.
[file] stream level seek from 2122888356 to 5774
[mkv] All headers are parsed!
[demux] Detected file format: Matroska
[cplayer] Opening done: test.mkv
[find_files] Loading external files in .
[mkv] select track 0
[mkv] select track 1
[cplayer]  (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
[cplayer]  (+) Audio --aid=1 --alang=fre (*) 'French' (aac 2ch 48000Hz)
[cplayer]      Audio --aid=2 --alang=heb 'Hebrew' (aac 2ch 48000Hz)
[cplayer]      Subs  --sid=1 --slang=fre 'French' (subrip)
[vo/gpu] Probing for best GPU context.
[cplayer] Error opening/initializing the selected video_out (--vo) device.
[mkv] deselect track 0
[cplayer] Video: no video
[ad] Codec list:
[ad]     aac - AAC (Advanced Audio Coding)
[ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[ad] Opening decoder aac
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: aac (AAC (Advanced Audio Coding))
[user_filter_wrapper] Setting option 'graph' = 'acompressor=level_in=0.4:attack=30:release=300:threshold=-20dB:ratio=20:makeup=15dB' (flags = 0)
[af] User filter list:
[af]   lavfi (lavfi.00)
[cplayer] Starting playback...
[cplayer] EOF code: 6  
[cplayer] finished playback, something happened (reason 4)
[cplayer] 
[cplayer] Exiting... (Errors when loading file)
```

**Comment by Akemi** [comment]
please post a full log like. a log file can be made with `--logfile=PATH_TO_FILE`. it should be equivalent to `-v -v` (twice).

otherwise also try with `--no-config`.

**Comment by Akemi** [comment]
tbh this isn't an issue with the build script but a runtime problem. the mpv issue tracker would be the proper place to ask.

**Comment by dbkblk** [comment]
Thank you for the help. You may be right, this is a runtime problem.
Still, I have tried to launch with the config or without, and the logs aren't that more explicit.

[mpv_config.log](https://github.com/mpv-player/mpv-build/files/6288180/mpv_config.log)
[mpv_noconfig.log](https://github.com/mpv-player/mpv-build/files/6288181/mpv_noconfig.log)

**Comment by Akemi** [comment]
seems like you build your mpv without any kind of linux supported backend (opengl, vulkan, etc) so it can't auto probe anything.

it probably doesn't find the dev packages you need. they need to be installed separately via your package manager. since i am not on linux i can't tell you the specific package names.

**Comment by dbkblk** [comment]
Thank you for the clue. I'll try to find how to build it and will report it there!

**Comment by dbkblk** [comment]
A HUGE thank you @Akemi :) I managed to fix it thanks to your clue!

So for those openSuse users here:

- Enable the source repository (Yast -> Software Repositories -> Enable openSUSE-Tumbleweed-Source). You don't have to set it on autorefresh, but do it manually one time.
- Then install the mpv build dependencies: 
`sudo zypper si mpv`
- Then rebuild using mpv-build:
`./rebuild -j4`

It also fixed my svp4linux problem, so everything is perfect now :)

**Comment by Akemi** [comment]
you are welcome.
