### ISSUE TITLE
Cannot build MPV - No OpenGL video output found or enabled

### ISSUE THREAD

**Issue by Phxntxm** [mpv-player/mpv-build#162]
System: Ubuntu 21.04

I'm just trying to run this as the instructions say in the readme, but I don't really know what I'm doing and things are not clear to someone who doesn't know this stuff well. There's a ton of requirements that are very wishy-washily mentioned, but I've no idea how to actually find the right packages. I'm sure I'm just missing packages to build this, but after days of searching these errors cannot figure it out. This is the output I have with no ffmpeg/mpv options... just trying the default setup to test this, just after a git clone and `./rebuild -j4`

https://mystb.in/MessageCoordinationTeach.properties

**Comment by LaserEyess** [comment]
You're missing development headers for most things. For example neither wayland nor xorg were detected, so it didn't even try to look for openGL. You need to get `*-dev` packages for these things e.g. `xorg-xserver-dev` (not really sure what these are called on ubuntu).

**Comment by Phxntxm** [comment]
That was it, I got that going and it built properly now... but... this build doesn't have any kind of actual clickable controls. Is there a way I can get that just like doing `apt-get install mpv` does?

**Comment by avih** [comment]
> doesn't have any kind of actual clickable controls

You're most probably missing lua. mpv supports lua 5.1 or 5.2 or jit. Like before - you need the -dev package. Check the output of the configure step to see if lua is found and enabled.

**Comment by Phxntxm** [comment]
Thanks for helpin out a noob with this stuff guys, got it all going. I appreciate it!
