### ISSUE TITLE
mpv-build fails to find static version of dav1d

### ISSUE THREAD

**Issue by BlueSwordM** [mpv-player/mpv-build#166]
**Describe the bug**
When configured normally, mpv-build's ffmpeg fails to find the dav1d version when the decoder is built with only static libraries in mind.
When building mpv-build, the usual error pops up:
`ERROR: dav1d >= 0.5.0 not found using pkg-config`

**To Reproduce**
1. Build dav1d according to the instructions found in here, but change meson's default library building process to `--default-library=static`
https://code.videolan.org/videolan/dav1d
2. Start building mpv normally with `--enable-libdav1d` in the ffmpeg options.

**Expected behavior**
Like externally built ffmpeg, mpv-build's ffmpeg should be able to find the dav1d package statically built using pkgconfig.

**Required Information**

mpv-build with mpv Git as of September 5th 2021.
libdav1d 0.9.2

Operating system:
Openmandriva 4.3 RC with Kernel 5.13

**Console Output**

Build log from config.log:
https://pastebin.com/KLcFXRv1

**Comment by BlueSwordM** [comment]
Has anyone encountered this issue?

**Comment by BlueSwordM** [comment]
The issue has been fixed on my end.

I built dav1d with Clang/LLVM statically using LTO, and GCC wasn't having any of it with that.

I just added ``--cc=clang --cxx=clang++` to the ffmpeg options, and that fixed everything.

**Comment by nanhui69** [comment]
just sudo apt-get install libdav1d-dev solve the problem

**Comment by shine-xia** [comment]
I met this same problem too when building ffmpeg with static lib of dav1d.
I analyzed the config.log and found the information below:
```
/usr/bin/ld: ../dav1d/lib/linux/x86_64/libdav1d.a(lib.c.o): in function close_internal': lib.c:(.text.unlikely+0x210): undefined reference to pthread_join'
/usr/bin/ld: ../dav1d/lib/linux/x86_64/libdav1d.a(lib.c.o): in function dav1d_open': lib.c:(.text.unlikely+0x538): undefined reference to pthread_once
```
/usr/bin/ld: lib.c:(.text.unlikely+0x5bb): undefined reference to dlsym' /usr/bin/ld: lib.c:(.text.unlikely+0x5e3): undefined reference to pthread_attr_setstacksize'`
So adding "-lpthread -ldl" in file "dav1d.pc"  solved this problem.
