### ISSUE TITLE
About the compiled mpv-1.dll file

### ISSUE THREAD

**Issue by ITSweets** [mpv-player/mpv-build#167]
Hi. I am trying to compile libmpv, I compile according to compile-windows.md, everything is going well. But I found that the size of the compiled mpv-1.dll is only about 10 mb, while the size of the mpv-1.dll in libmpv I downloaded from sourceforge is at least 60 mb. What's the situation? In addition, how to modify the name of the generated mpv-1.dll? For example, change to MpvCore.dll.
Looking forward to your reply.

**Comment by Dudemanguy** [comment]
The size of the compiled library can vary depending on what options you pass and so on. If you want to change the name of the dll, you can just rename it.
