### ISSUE TITLE
scripts/mpv-install - Failed to change directory

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv-build#176]
Hello! After cloning this repository, changing to `mpv-build`, and running `sudo ./install`, I'm greeted with the following error:
```
scripts/mpv-install: 4: cd: can't cd to mpv
```

**Comment by CounterPillow** [comment]
Well, you gotta build it first with `./rebuild -jnumberofcoreshere`

**Comment by Dudemanguy** [comment]
OP is a ghost and this seems like user error.
