### ISSUE TITLE
Waflib error: module not found 

### ISSUE THREAD

**Issue by Anonymous78910** [mpv-player/mpv-build#178]
I just experienced this error while building

> File "~/mpv-build/mpv/.waf3-2.0.20-36f5354d605298f6a89c09e0c7ef6c1d/waflib/./Configure.py", line 6, in
> from waflib import
> ConfigSet,Utils,Options,Logs,Context,Build,Errors
> ModuleNotFoundError: No module named 'waflib'

**Comment by Dudemanguy** [comment]
Waf support is no more.
