### ISSUE TITLE
./autogen.sh is not found

### ISSUE THREAD

**Issue by Animationss** [mpv-player/mpv-build#179]
After running `./rebuild -j4` everything seemed to go well until the last 2 messages 

https://pastebin.com/8SLkr3QW

So I attempted to `./build` and i got the same message 

```
Running autoreconf...
./autogen.sh: 3: autoreconf: not found
```
Not sure what to do please help

**Comment by avih** [comment]
You need to install require build tools for the various packages. Specifically here, it's probably libass needing the autoconf package (and gcc and other development tools).
