### ISSUE TITLE
The project was not configured: run "waf configure" first!

### ISSUE THREAD

**Issue by Animationss** [mpv-player/mpv-build#180]
After running the command `./build` and `./rebuild` many times `sudo ./install` refuses to work 

https://pastebin.com/AJF5xh6c

At the end of the log I noticed something seemed to go wrong, No idea what to do though

**Comment by sirneb** [comment]
I had the same issue with Ubuntu 21.10. 

Apparently, there's a big section on building dependencies in the README:
https://github.com/mpv-player/mpv-build#instructions-for-debian--ubuntu-package

Specifically:
```
apt-get install devscripts equivs
mk-build-deps -s sudo -i
dpkg-buildpackage -uc -us -b -j4
```
then finally running `sudo ./install`

**Comment by Dudemanguy** [comment]
Waf support no longer exists.
