### ISSUE TITLE
Stuck in a loop of futility

### ISSUE THREAD

**Issue by therealmrzippy** [mpv-player/mpv-build#181]
I'm trying to use the scripts to build MPV etc... but when I get to the rebuild stage, no matter what, it fails. Despite not having used WAF, i get an error stating "The Project was not configured: run "waf configure" first!"

Problem is..waf doesn't run. when typing in ./waf configure from the mpv-build directory (running from a sudo -i terminal prompt), I get the following:

-bash: ./waf no such file or directory

Doing some digging I find waf in the mpv-build/mpv directory. CD to mpv-build/mpv and then I can run ./waf configure... but now it fails when checking for 

mujs
lua-5.1
libass

yet all of those are present. 

I'm in this seemingly endless loop of missing dependencies, broken packages.

This is running on RaspiOS Bullseye, 64 bit. Fresh install. I've tried deleting the directory 

(rm -R mpv-build) from the ~ directory as root.. and then restarting the process..but then rebuild fails looking for harfbuzz. 

Suggestions?

**Comment by therealmrzippy** [comment]
still getting an error when it runs ./rebuild - harfbuzz not found. so it can't complete.
ideas?

**Comment by therealmrzippy** [comment]
i get an error asking for harfbuzz during the ./rebuild stage.. so it fails, and then I am stuck in this loop of doom. 

during the ./rebuild step, i get 

"No package 'harfbuzz' found"

and then a blurb about adjusting PKG_CONFIG path blah blah. running as user, not root. Same problem with root though,

**Comment by sfan5** [comment]
Did you install `libharfbuzz-dev` (and the other dependencies)?

**Comment by CounterPillow** [comment]
run `sudo apt-get build-dep mpv` to make your package manager install all the necessary build time dependencies.

**Comment by Pysis868** [comment]
`sudo dnf builddep mpv` for Fedora.
