### ISSUE TITLE
mpv-build fails with compilation error

### ISSUE THREAD

**Issue by rpfeiffer** [mpv-player/mpv-build#191]
Hello!
I tried to update mpv by using the mpv-build framework. I am using clang-14, so I set the environment variables CC and CXX to clang-14 and clang++-14. The compile process halts with an error:

…
[154/247] Compiling video/out/vo_caca.c
[155/247] Compiling video/out/drm_atomic.c
[156/247] Compiling stream/stream_edl.c
[157/247] Compiling demux/demux_cue.c
../video/out/drm_common.c:562:40: error: implicit declaration of function 'drmIsKMS' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        const int is_kms = fd != -1 && drmIsKMS(fd);
                                       ^
1 error generated.

Waf: Leaving directory `/usr/src/build/mpv-build/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)

My system is a Debian 11 (backports packages). Clang is installed from their Debian repository. I can't find the function drmIsKMS() in the sources, but maybe I looked into the wrong folders.

**Comment by CounterPillow** [comment]
See https://github.com/mpv-player/mpv/pull/10511
