### ISSUE TITLE
(+ scripts/mpv-bootstrap) failed to download waf 1.9.8

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#193]
Hello,

on an older computer 
would like to install mpv player,

but the build fails due 
to possibly old libraries

+ local branch=master
+ [ -z  ]
+ [ -d config/ ]
+ [ -f config/branch-libplacebo ]
+ do_gitmaster libplacebo
+ set -ex
+ cd libplacebo
+ git checkout origin/master
HEAD is now at 0ce3fa4... d3d11: fix documentation
+ git remote prune origin
+ checkout mpv master
+ local branch=master
+ [ -z  ]
+ [ -d config/ ]
+ [ -f config/branch-mpv ]
+ cat config/branch-mpv
+ branch=@v0.25.0
+ do_fixedref mpv v0.25.0
+ cd mpv
+ git checkout v0.25.0
HEAD is now at eabba2d... Release 0.25.0
+ do_update_debian_versions
+ scripts/debian-update-versions
+ do_bootstrap
+ scripts/mpv-bootstrap
Downloading https://waf.io/waf-1.9.8...
Download failed.
Downloading http://www.freehackers.org/~tnagy/release/waf-1.9.8...
Download failed.
Could not download waf-1.9.8.

now i have downloaded waf-1.9.8 and kindly asking where it should be put and how inside the mpv-build directory,

thank you very much.

**Comment by sfan5** [comment]
Why are you trying to build an mpv version that is five years out of date?

**Comment by kevmitch** [comment]
Put waf in the `mpv` direrectory.
