### ISSUE TITLE
Still getting libplacebo not found using pkg-config error

### ISSUE THREAD

**Issue by kwaaak** [mpv-player/mpv-build#200]
@kevmitch I've adapted the scripts to support the `--wipe` functionality from your PR.
`-lstd++` I added to both `ffmpeg` and `mpv` as they may both link against `libplacebo`, which may have `glslang` enabled.

I'd get an error from pkg-config when configuring ffmpeg without `-lstd++`:
```
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /home/zeromind/src/github.com/zeromind/mpv-build/build_libs/lib/libplacebo.a(glsl_glslang.cc.o): undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ERROR: libplacebo >= 4.192.0 not found using pkg-config
```

_Originally posted by @zeromind in https://github.com/mpv-player/mpv-build/issues/188#issuecomment-1226619797_
      

I was still getting this error, everything builds fine after doing a `sudo apt remove glslang-dev`
I assume libplacebo is built without it now and successfully picked up by ffmpeg's configure

Manually checking with pkg-config returned no error, maybe it is worth investigating more because the error is not what it seems.

**Comment by thebombzen** [comment]
Copying and pasting a comment doesn't tell us anything. Please follow the issue template.
