### ISSUE TITLE
Can't find the executable to be copied in /usr/local/bin

### ISSUE THREAD

**Issue by niels0n** [mpv-player/mpv-build#205]
Hi, I'm on Debian, I followed the instructions, but after `./rebuild -j4` I really can't find the executable anywhere.
Sorry if this is stupid, but where am I supposed to find it?

**Comment by CounterPillow** [comment]
> Hi, I'm on Debian

my condolences.

It's in `./mpv/build/mpv`

**Comment by niels0n** [comment]
> my condolences.

Yeah, right? I thought that was not so bad all things considered...until now. It's probably a masochistic choice, so do you have any distro to suggest? lol

Anyway, since I do not have the folder...

> If it's not there, your build probably failed, and you should provide a log file.

`+ git pull --rebase
Already up to date.
+ do_clone_all
+ do_clone ffmpeg https://github.com/FFmpeg/FFmpeg.git
+ set -ex
+ test -e ffmpeg
+ git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
Cloning into 'ffmpeg'...
remote: Enumerating objects: 683181, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 683181 (delta 0), reused 1 (delta 0), pack-reused 683177
Receiving objects: 100% (683181/683181), 333.96 MiB | 5.68 MiB/s, done.
Resolving deltas: 100% (536409/536409), done.
+ cd ffmpeg
+ git remote set-url origin https://github.com/FFmpeg/FFmpeg.git
+ git fetch
+ git submodule update --init
+ do_clone libass https://github.com/libass/libass.git
+ set -ex
+ test -e libass
+ git clone https://github.com/libass/libass.git libass
Cloning into 'libass'...
remote: Enumerating objects: 9684, done.
remote: Counting objects: 100% (629/629), done.
remote: Compressing objects: 100% (269/269), done.
remote: Total 9684 (delta 423), reused 449 (delta 349), pack-reused 9055
Receiving objects: 100% (9684/9684), 3.35 MiB | 3.59 MiB/s, done.
Resolving deltas: 100% (6649/6649), done.
+ cd libass
+ git remote set-url origin https://github.com/libass/libass.git
+ git fetch
+ git submodule update --init
+ do_clone libplacebo https://github.com/haasn/libplacebo.git
+ set -ex
+ test -e libplacebo
+ git clone https://github.com/haasn/libplacebo.git libplacebo
Cloning into 'libplacebo'...
remote: Enumerating objects: 16132, done.
remote: Counting objects: 100% (5597/5597), done.
remote: Compressing objects: 100% (1235/1235), done.
remote: Total 16132 (delta 4353), reused 5377 (delta 4238), pack-reused 10535
Receiving objects: 100% (16132/16132), 5.14 MiB | 4.00 MiB/s, done.
Resolving deltas: 100% (12154/12154), done.
+ cd libplacebo
+ git remote set-url origin https://github.com/haasn/libplacebo.git
+ git fetch
+ git submodule update --init
Submodule '3rdparty/Vulkan-Headers' (https://github.com/KhronosGroup/Vulkan-Headers) registered for path '3rdparty/Vulkan-Headers'
Submodule '3rdparty/glad' (https://github.com/Dav1dde/glad) registered for path '3rdparty/glad'
Submodule '3rdparty/jinja' (https://github.com/pallets/jinja) registered for path '3rdparty/jinja'
Submodule '3rdparty/markupsafe' (https://github.com/pallets/markupsafe) registered for path '3rdparty/markupsafe'
Submodule 'demos/3rdparty/nuklear' (https://github.com/Immediate-Mode-UI/Nuklear.git) registered for path 'demos/3rdparty/nuklear'
Cloning into '/home/andrea/mpv-build/libplacebo/3rdparty/Vulkan-Headers'...
Cloning into '/home/andrea/mpv-build/libplacebo/3rdparty/glad'...
Cloning into '/home/andrea/mpv-build/libplacebo/3rdparty/jinja'...
Cloning into '/home/andrea/mpv-build/libplacebo/3rdparty/markupsafe'...
Cloning into '/home/andrea/mpv-build/libplacebo/demos/3rdparty/nuklear'...
Submodule path '3rdparty/Vulkan-Headers': checked out '88ebcb08cb131ca278af6e7a26887fe59b25ec1c'
Submodule path '3rdparty/glad': checked out '525eddb7e04bc4008b691fb38a6d31bf3cad684c'
Submodule path '3rdparty/jinja': checked out 'b08cd4bc64bb980df86ed2876978ae5735572280'
Submodule path '3rdparty/markupsafe': checked out 'b90a42e08121f2cd9ff5dd8e5eef32a70e9959e3'
Submodule path 'demos/3rdparty/nuklear': checked out '3e91905e82c3cad01435d4a8a660a30e7f73c94a'
+ do_clone mpv https://github.com/mpv-player/mpv.git
+ set -ex
+ test -e mpv
+ git clone https://github.com/mpv-player/mpv.git mpv
Cloning into 'mpv'...
remote: Enumerating objects: 294191, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 294191 (delta 115), reused 182 (delta 80), pack-reused 293954
Receiving objects: 100% (294191/294191), 96.31 MiB | 5.58 MiB/s, done.
Resolving deltas: 100% (231854/231854), done.
+ cd mpv
+ git remote set-url origin https://github.com/mpv-player/mpv.git
+ git fetch
+ git submodule update --init
+ checkout ffmpeg master
+ local branch=master
+ [ -z  ]
+ [ -d config/ ]
+ do_gitmaster ffmpeg
+ set -ex
+ cd ffmpeg
+ git checkout origin/master
Note: switching to 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 2378cbe36b avfilter/vf_showinfo: add support for Ambient Viewing Environment side data
+ git remote prune origin
+ checkout libass master
+ local branch=master
+ [ -z  ]
+ [ -d config/ ]
+ do_gitmaster libass
+ set -ex
+ cd libass
+ git checkout origin/master
Note: switching to 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a943ef5 configure: support x86 assembly on GNU Hurd
+ git remote prune origin
+ checkout libplacebo master
+ local branch=master
+ [ -z  ]
+ [ -d config/ ]
+ do_gitmaster libplacebo
+ set -ex
+ cd libplacebo
+ git checkout origin/master
Note: switching to 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f9dacd3 vulkan: fix typo in log message
+ git remote prune origin
+ checkout mpv master
+ local branch=master
+ [ -z  ]
+ [ -d config/ ]
+ do_gitmaster mpv
+ set -ex
+ cd mpv
+ git checkout origin/master
Note: switching to 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6cdce9e18e wayland: store presentation feedbacks in a pool
+ git remote prune origin
+ do_update_debian_versions
+ scripts/debian-update-versions
+ do_bootstrap
+ scripts/mpv-bootstrap
Downloading https://waf.io/waf-2.0.24...
Checksum verified.
'distclean' finished successfully (0.002s)
Using libplacebo options: -Ddefault_library=static -Dtests=false -Ddemos=false
scripts/libplacebo-config: 30: meson: not found
`

**Comment by nicolaasjan** [comment]
`pip install meson` ?

**Comment by CounterPillow** [comment]
or install meson through your package manager (if it has a new enough version)

**Comment by nicolaasjan** [comment]
> (if it has a new enough version)

That could be an issue on Debian. 😀️
Building MPV on my Debian 10 VM failed for lots of reasons...

**Comment by eli-schwartz** [comment]
Debian 10 is definitely not new enough to get the required Meson version, theirs is way too old.

Even Debian 11 would also require you to enable backports to get the required Meson version.

However, installing Meson from pip should work fine...

**Comment by niels0n** [comment]
Sorry for the delay, I was reinstalling Arch lol anyway for the records the Meson in Debian 11 is too old indeed and it didn't work. Yes, probably installing it from pip as @nicolaasjan said is the solution. Thank you all!

**Comment by niels0n** [comment]
Sorry for the delay, I was reinstalling Arch lol anyway for the records the Meson in Debian 11 is too old indeed and it didn't work. Yes, probably installing it from pip as @nicolaasjan said is the solution. Thank you all!
