### ISSUE TITLE
git master build with meson fails

### ISSUE THREAD

**Issue by razvaneduard** [mpv-player/mpv-build#212]
### mpv version and platform versions
Ubuntu 22.04.1 LTS
mpv git master

### Reproduction steps
this work without issues
BUILDSYSTEM=waf   ./rebuild -j12

but building using meson fail at final step.
I use helper scripts.

ninja --version
1.11.1.git.kitware.jobserver-1
meson -v
1.0.0

ffmpeg_options
--enable-libx264
--enable-libx265
--enable-libmp3lame
--enable-libfdk-aac
--enable-nonfree
--enable-libvorbis
--enable-libvpx
--enable-libopus
--enable-libtheora
--enable-libpulse
--enable-gnutls
--enable-libcaca

mpv_options
-Dprefer_static=true
-Dx11=enabled
-Dwayland=disabled

console output
....
....
[242/242] Linking target mpv
FAILED: mpv 
...
huge number of 'undefined reference' reported
...
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

### Expected behavior
I saw waf was deprecated and now I should use meson, but this fail

### Log file
[meson-log.txt](https://github.com/mpv-player/mpv/files/10486730/meson-log.txt)
[output.txt](https://github.com/mpv-player/mpv/files/10486734/output.txt)

**Comment by razvaneduard** [comment]
without 
-Dprefer_static=true
the build complete.

So I shouldn't use prefer-static, right?

**Comment by Dudemanguy** [comment]
Right, you don't need it unless you really want to statically link absolutely everything possible (which is not the point of mpv-build).

**Comment by razvaneduard** [comment]
thank you for the help
