### ISSUE TITLE
No binary after successful(?) rebuild on Fedora

### ISSUE THREAD

**Issue by AaronStiff** [mpv-player/mpv-build#218]
After installing all the dependencies required and getting what I thought was a successful rebuild, there's no `./mpv/build/mpv`, and `sudo ./install` obviously fails.

Logs: 
[logs.txt](https://github.com/mpv-player/mpv-build/files/11129605/logs.txt)

**Comment by CounterPillow** [comment]
You didn't have a successful build.

> nasm/yasm not found or too old. Use --disable-x86asm for a crippled build.

install nasm or yasm.

**Comment by AaronStiff** [comment]
Ah, I see. Thought (read:wished) that was just a warning :) Thanks!

**Comment by jeeb** [comment]
Recent nasm is generally recommended for FFmpeg, so go that route :) .

**Comment by AaronStiff** [comment]
`yasm-devel` is in the Fedora package, but I'm not seeing a devel version of nasm...

**Comment by CounterPillow** [comment]
You don't need a devel version, you need the actual `nasm` binary which will be in the regular package.

**Comment by AaronStiff** [comment]
Cool, thanks!
