### ISSUE TITLE
(Ubuntu) meson: error: unrecognized arguments: --enable-vapoursynth --enable-libmpv-shared

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#219]
Hello ,

am getting this error,
but having meson and ninja installed via python3-pip.

please indicate me the right direction 

`make: Leaving directory '/home/rich/Programs/mpv-build/ffmpeg_build'
Using mpv options: -Dc_link_args='-Wl,-Bsymbolic' --enable-vapoursynth --enable-libmpv-shared
usage: meson [-h]
             {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help}
             ...
meson: error: unrecognized arguments: --enable-vapoursynth --enable-libmpv-shared
`

[options.zip](https://github.com/mpv-player/mpv-build/files/11141106/options.zip)

**Comment by Dudemanguy** [comment]
Use meson conforming arguments: `-Dvapoursynth=enabled` and `-Dlibmpv=true`.

**Comment by mrkapqa** [comment]
did not include those,
dont know what you mean,

building instructions were as follows

- echo --enable-libx264 >> ffmpeg_options
echo --enable-nvdec >> ffmpeg_options
echo --enable-vaapi >> ffmpeg_options
echo --enable-vapoursynth >> mpv_options
echo --enable-libmpv-shared >> mpv_options
./rebuild -j4

**Comment by Dudemanguy** [comment]
>echo --enable-vapoursynth >> mpv_options
>echo --enable-libmpv-shared >> mpv_options

These are dated and from the old waf build. Pass meson conforming options instead like I said.

**Comment by mrkapqa** [comment]
ok, thanks, so would i then need to 

echo enable --Dvapoursynth=enabled >> mpv_options
echo enable ---Dlibmpv=true >> mpv_options

would it function if instead would try with

`BUILDSYSTEM=waf ./rebuild -j4` ?

**Comment by mrkapqa** [comment]
thanks, with your instructins it functioned.

all the best.
