### ISSUE TITLE
mpv-build fatal error: EGL/eglplatform.h: No such file or directory

### ISSUE THREAD

**Issue by Ryzen360** [mpv-player/mpv-build#230]
mpv-build-master

mpv 0.38.0-UNKNOWN

    d3d11     : NO
    javascript: YES
    libmpv    : NO
    lua       : YES
    opengl    : YES
    vulkan    : YES
    wayland   : YES
    x11       : YES

  User defined options
    buildtype : release

Found ninja-1.11.1 at /usr/bin/ninja
INFO: autodetecting backend as ninja                                                                
INFO: calculating backend command to run: /usr/bin/ninja -C /home/deck/mpv-build-master/mpv/build -j 4
ninja: Entering directory `/home/deck/mpv-build-master/mpv/build'
[223/314] Compiling C object libmpv.so.2.3.0.p/video_out_gpu_next_context.c.o
FAILED: libmpv.so.2.3.0.p/video_out_gpu_next_context.c.o 
cc -Ilibmpv.so.2.3.0.p -I. -I.. -Icommon -Ietc -Iplayer/javascript -Iplayer/lua -Isub -Ivideo/out -I/home/deck/mpv-build-master/build_libs/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/fribidi -I/usr/include/libxml2 -I/usr/include/lua5.2 -I/usr/include/uchardet -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -std=c11 -O3 -D_FILE_OFFSET_BITS=64 -Werror=implicit-function-declaration -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -Wno-cast-function-type -Wempty-body -Wdisabled-optimization -Wstrict-prototypes -Wno-format-zero-length -Wno-redundant-decls -Wvla -Wno-format-truncation -Wimplicit-fallthrough -fno-math-errno -Wformat -Werror=format-security -Wundef -Wmissing-prototypes -Wshadow -Wno-switch -Wparentheses -Wpointer-arith -Wno-pointer-sign -Wno-unused-result -D_GNU_SOURCE -fPIC -pthread -D_REENTRANT -DPL_HAVE_PTHREAD -DPTHREAD_HAS_SETCLOCK -DPL_STATIC -MD -MQ libmpv.so.2.3.0.p/video_out_gpu_next_context.c.o -MF libmpv.so.2.3.0.p/video_out_gpu_next_context.c.o.d -o libmpv.so.2.3.0.p/video_out_gpu_next_context.c.o -c ../video/out/gpu_next/context.c
In file included from ../video/out/gpu_next/context.c:45:
/usr/include/EGL/egl.h:20:10: fatal error: EGL/eglplatform.h: No such file or directory
   20 | #include <EGL/eglplatform.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[226/314] Compiling C object libmpv.so.2.3.0.p/video_out_vo_gpu_next.c.o
../video/out/vo_gpu_next.c: In function 'update_render_options':
../video/out/vo_gpu_next.c:2218:5: warning: 'tone_mapping_param' is deprecated [-Wdeprecated-declarations]
 2218 |     pars->color_map_params.tone_mapping_param = opts->tone_map.curve_param;
      |     ^~~~
In file included from /home/deck/mpv-build-master/build_libs/include/libplacebo/renderer.h:25,
                 from /home/deck/mpv-build-master/build_libs/include/libplacebo/options.h:21,
                 from ../video/out/vo_gpu_next.c:24:
/home/deck/mpv-build-master/build_libs/include/libplacebo/shaders/colorspace.h:303:36: note: declared here
  303 |     PL_DEPRECATED_IN(v6.311) float tone_mapping_param;        // see `tone_constants`
      |                                    ^~~~~~~~~~~~~~~~~~
../video/out/vo_gpu_next.c:2219:5: warning: 'tone_mapping_param' is deprecated [-Wdeprecated-declarations]
 2219 |     if (isnan(pars->color_map_params.tone_mapping_param)) // vo_gpu compatibility
      |     ^~
/home/deck/mpv-build-master/build_libs/include/libplacebo/shaders/colorspace.h:303:36: note: declared here
  303 |     PL_DEPRECATED_IN(v6.311) float tone_mapping_param;        // see `tone_constants`
      |                                    ^~~~~~~~~~~~~~~~~~
../video/out/vo_gpu_next.c:2220:9: warning: 'tone_mapping_param' is deprecated [-Wdeprecated-declarations]
 2220 |         pars->color_map_params.tone_mapping_param = 0.0;
      |         ^~~~
/home/deck/mpv-build-master/build_libs/include/libplacebo/shaders/colorspace.h:303:36: note: declared here
  303 |     PL_DEPRECATED_IN(v6.311) float tone_mapping_param;        // see `tone_constants`
      |                                    ^~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
(1)(deck@steamdeck mpv-build-master)$ ^C
(130)(deck@steamdeck mpv-build-master)$

**Comment by sfan5** [comment]
You need the mesa development headers (GL, EGL and possibly GLX).
