### ISSUE TITLE
Support js script

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv-build#232]
By default, mpv-build only support lua scripts. Is it possible to also add support for js scripts?

**Comment by CounterPillow** [comment]
> By default, mpv-build only support lua scripts.

This is completely false. mpv-build does not treat Lua or JS any different, in that it does not vendor either of them. mpv's build process will pick up Lua and JS if they are installed and dev headers are present. Please install mujs and its development headers on your system.

**Comment by ahaoboy** [comment]
Thank you
