### ISSUE TITLE
m4 keeps insisting on installing already installed dev tools

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv-build#236]
Every time running a full mpv-build, the following dialog box is shown, even though the developer tools are already installed.

> The "m4" command requires the command line developer tools. Would you like to install the tools now? 

The installer keeps going (and succeeding) in the background, without any user interaction, so the request seems unnecessary to begin with.

Is this a bug or how is one to understand this?

**Comment by Akemi** [comment]
https://github.com/Homebrew/homebrew-core/issues/165388

seems like either you are still using broken dev tools, or apple broke them again.

**Comment by forthrin** [comment]
Any relevant (version) checks, etc. to do? Or just ignore until it's fixed elsewhere?

**Comment by Akemi** [comment]
seems like it's from CLT 15.3 onwards, see the fix in homebrew https://github.com/Homebrew/brew/blob/master/Library/Homebrew/shims/mac/super/m4. if it's still broken in 15.4, you probably need to wait till 16.

though this isn't really a problem on our end, so this should probably be closed.

**Comment by Akemi** [comment]
you are welcome.
