### ISSUE TITLE
Compile Fails in Raspberry Pi

### ISSUE THREAD

**Issue by acpadhi** [mpv-player/mpv-build#41]
Trying to compile in Raspberry since someone in Mplayer2 IRC suggested me to use MPV instead of Mplayer or Mplayer2 since both of the communities are almost inactive now. No Binary of MPV exists in Raspberry Pi Repos as far as I know, the only one that I found was a deb file somewhere and it wanted a higher version of libass. In total it is nothing but a real pain for first time users to be not able to get binaries readily available. Compiling such a beast and complex app is real pain and long process.

Got your build script and tried running it. Got errors like this :

First it complained about aclocal. but then I installed automake from repos. So that error was resolved.

After automake, ran ./build again to get below errors.
Errors towards the end of the screen : 

INSTALL home/pi/mpv/mpv-build/ffmpeg/libavutil/lzo.h
INSTALL libavutil/avconfig.h
INSTALL libavutil/ffversion.h
INSTALL libavutil/libavutil.pc
make: Leaving directory `/home/pi/mpv/mpv-build/ffmpeg_build'
Usable autoreconf found, running
configure.ac:50: installing`./install-sh'
configure.ac:50: installing `./missing'
bin/Makefile.am: installing`./depcomp'
charset/Makefile.am:1: Libtool library used but `LIBTOOL' is undefined
charset/Makefile.am:1:   The usual way to define`LIBTOOL' is to add `LT_INIT'
charset/Makefile.am:1:   to`configure.ac' and run `aclocal' and`autoconf' again.
charset/Makefile.am:1:   If `LT_INIT' is in`configure.ac', make sure
charset/Makefile.am:1:   its definition is in aclocal's search path.
lib/Headers.mk:22: shell cat $(top_srcdir: non-POSIX variable name
lib/Headers.mk:22: (probably a GNU make extension)
doc/Makefile.am:26:   `lib/Headers.mk' included from here
lib/Headers.mk:22: shell cat $(top_srcdir: non-POSIX variable name
lib/Headers.mk:22: (probably a GNU make extension)
lib/Makefile.am:28:`lib/Headers.mk' included from here
lib/Makefile.am:3: Libtool library used but `LIBTOOL' is undefined
lib/Makefile.am:3:   The usual way to define`LIBTOOL' is to add `LT_INIT'
lib/Makefile.am:3:   to`configure.ac' and run `aclocal' and`autoconf' again.
lib/Makefile.am:3:   If `LT_INIT' is in`configure.ac', make sure
lib/Makefile.am:3:   its definition is in aclocal's search path.
test/Makefile.am:30: `%'-style pattern rules are a GNU make extension
Makefile.am: installing`./INSTALL'
autoreconf: automake failed with exit status: 1

Any ideas on how this can be fixed ?

**Comment by 97-109-107** [comment]
I fixed this error on raspberrian by doing:
````
sudo apt-get install libtool
libtoolize
````
source: https://stackoverflow.com/questions/18978252/error-libtool-library-used-but-libtool-is-undefined
