### ISSUE TITLE
Playing YouTube videos doesn't work unless --enable-gnutls is enabled explicitly

### ISSUE THREAD

**Issue by runeksvendsen** [mpv-player/mpv-build#54]
I'm not sure if this is a bug, but I thought I'd report it anyway, in case it isn't intended behavior.

When I build mpv from scratch using the mpv-build repo in a fresh Ubuntu 14.04 container, the resulting binary doesn't support https streams. Error:

    https protocol not found, recompile with openssl or gnutls enabled

This is fixed by putting the string "--enable-gnutls" in the file `ffmpeg_options`, but I assume YouTube support (and support for fetching data over HTTPS in general) should be turned on by default.

This is the Dockerfile I'm using:

    FROM ubuntu:14.04
    MAINTAINER Rune K. Svendsen

    ENV BPATH /opt/mpv/

    RUN sed -i -e 's/# deb/deb/g' /etc/apt/sources.list
    RUN apt-get update && apt-get install --yes --force-yes git python-minimal
    RUN mkdir -p $BPATH

    RUN cd $BPATH && git clone https://github.com/mpv-player/mpv-build.git && cd mpv-build/ && ./update && apt-get install --yes --force-yes devscripts equivs && rm -f mpv-build-deps_*_*.deb && mk-build-deps -i -t "apt-get --yes --force-yes --no-install-recommends"

    RUN cd $BPATH/mpv-build/ && ./build -j$(nproc)

This will produce an mpv binary without HTTPS support. Adding the line

    RUN cd $BPATH/mpv-build/ && echo --enable-gnutls >> ffmpeg_options

to the Dockerfile (before running ./build) fixes this.

**Comment by wm4** [comment]
That's true. You can either enable openssl or gnutls. FFmpeg won't enable either of them by default (it won't even try autodetection), so it has to be done manually.

I wonder if we should enable one of these by default?

**Comment by runeksvendsen** [comment]
I definitely think we should enable it by default, in mpv-build. Being able to play YouTube videos is a killer feature of mpv. It should be there by default.

Whether it should be openssl or gnutls, though, I don't know.

**Comment by kevmitch** [comment]
The problem is that adding this will then *require* one of these libraries to be present for everyone building everywhere. It would also force the choice of which of the two libraries are used.

**Comment by wm4** [comment]
I see the following possibilities:
- enable one of them and require the user to have it installed
- write a small test that checks whether the lib is present (ugh)
- convince ffmpeg to add a configure option that does autodetection for it (ugh)
- build one of the libs with mpv-build (ugh)

**Comment by runeksvendsen** [comment]
I see. I didn't realize it was either forcing users to enable it or making it optional. In that case I'm not sure what to do. I guess you're better suited for deciding whether HTTPS support should be optional.

**Comment by mc4man** [comment]
Maybe you just mention it in the README.rst. It would seem anyone using  mpv-build  to build a binary would be responsible for configuring as they want or need.
Anyone using to do a .deb package build will get HTTPS support as it's in the control & rules file (via gnutls

**Comment by wm4** [comment]
>write a small test that checks whether the lib is present (ugh)

Went with this implementation. Fugly, but mpv-build is for making building mpv easier, after all.
