### ISSUE TITLE
Question: ffmpeg-config: Autodetect OpenSSL or GnuTLS?

### ISSUE THREAD

**Issue by moulei** [mpv-player/mpv-build#56]
Hi,

I noticed the recent change for fmpeg-config: Autodetect OpenSSL or GnuTLS...

I don't understand, with mpv being a media player, what do these changes mean?

thanks

**Comment by wm4** [comment]
For ``https://``.

**Comment by moulei** [comment]
Are you talking about MPV streaming media?

**Comment by kevmitch** [comment]
yes. most common example example is playing youtube videos

**Comment by moulei** [comment]
Ahhh ok, I thought I vaguely remembered reading about the Stream support being added in.

I just want a stand alone media player, so I'm assuming I don't need these changes then in ffmpeg-config and I can just disregard them.

Can someone please tell me for the ffmpeg --configure options, if there is one to disable streaming I can add to ```ffmpeg_options```?

thanks

**Comment by kevmitch** [comment]
You don't need to disable anything. If you don't have the libraries installed. It won't use them.

**Comment by moulei** [comment]
Which libraries are you referring to, and are these mentioned in any MPV README/INSTALL files?

thanks

**Comment by kevmitch** [comment]
the libraries are libopenssl or libgnutls 

their necessity for youtube-dl is documented in the mpv-build README.rst [here](https://github.com/mpv-player/mpv-build#dependencies)

**Comment by moulei** [comment]
Of course most distros have libopenssl or libgnutls, but I don't have youtube-dl, so I'm assuming just because I have openssl and lubgnutls, the mpv-build isn't going to automatically download it down and compile against it?

**Comment by kevmitch** [comment]
no, in fact even if your distro did have youtube-dl, it would probably be too old. 

on the plus side, youtube-dl doesn't need to be present at compile time since it is just called as if from the shell.

**Comment by moulei** [comment]
Hi kevmitch,

Ok, well I don't have youtube-dl installed, and I don't ever plan to do streaming with mpv, so I guess, no need to make the changes for ffmpeg-config?

Thanks for your time...
