### ISSUE TITLE
Use git clone --depth 1 for faster clones

### ISSUE THREAD

**Issue by postmodern** [mpv-player/mpv-build#62]
We don't need the entire commit history, `--depth 1` it!

**Comment by wm4** [comment]
The problem with this is that with --depth=1 the tags (apparently) do not match up anymore, so I'm not sure if this could work with the current scripts. If someone could verify whether this happens and/or has a workaround, that would be welcome.

**Comment by wm4** [comment]
Or maybe the problem is that it doesn't fetch all refs (so we can't list them locally). Do you have any interest in getting this to work?

**Comment by kevmitch** [comment]
For me,

    git clone --depth 1 https://github.com/FFmpeg/FFmpeg.git
    cd FFmpeg && git tag

returns nothing at all.

It seems that the fundamental is that git has no way of of cloning only metadata. For example 

    git log remotes/origin/master

will not do what you might expect/want in a shallow clone. There is a relevant [stackoverflow question](http://stackoverflow.com/questions/20055398/is-it-possible-to-get-commit-logs-messages-of-a-remote-git-repo-without-git-clon) essentially confirming this.

**Comment by postmodern** [comment]
I guess you'd want to `git clone/pull` the entire repo if you want to use a specific release. If you just want to use `HEAD`, `git clone --depth 1` should work.

**Comment by kevmitch** [comment]
this creates all kinds of problems when switching from one to the other

**Comment by postmodern** [comment]
Could run `git pull --tags` if switching to to a specific release?

**Comment by postmodern** [comment]
Actually, if you are building from a release, the script should download the `*.tar.gz` and extract them. If building from master, `git clone`.
