### ISSUE TITLE
Question: why is there both liblua5.2-dev & liblua5.1-dev in control

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv-build#64]
There are on separate lines so both are required ??

**Comment by kevmitch** [comment]
Because either one will work. They are separated by an "or" operator.

**Comment by kevmitch** [comment]
or wait, they're not. . .

**Comment by wm4** [comment]
Yeah, they should be separated with an or operator.

**Comment by kevmitch** [comment]
Ah, it was a fix for #30 which should no longer be a problem now that we no longer have quvi.
