### ISSUE TITLE
Mention librtmp in ffmpeg as possibly useful

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv-build#65]
Having it enabled can extend mpv's url support, typically it's enabled in a ffmpeg shared build but not that often in a static build.
Simple example in U.S. - 
mpv http://www.cbsnews.com/videos/dozens-killed-hundreds-hurt-in-china-warehouse-blast

**Comment by kevmitch** [comment]
I've added it to the list of debian dependencies.
