### ISSUE TITLE
Compilation error: "cannot find -liconv"

### ISSUE THREAD

**Issue by kevinlekiller** [mpv-player/mpv-build#66]
Running off ffmpeg master, mpv master branches, arch linux x86 64bit.

mpv was compiling fine 2 days ago.

I started getting this error today : `/usr/bin/ld: cannot find -liconv`

iconv.h : `4.0K -rw-r--r-- 1 root root 1.9K Sep  1 13:09 /usr/include/iconv.h`

Tried recloning mpv-build, same error.

Then I tried to reinstall glibc, but same thing.

Compiled/installed [libiconv](https://www.gnu.org/software/libiconv/), then mpv compiles, but when I run mpv it throws an error that it can't find the iconv shared library, and when colors would show in a terminal emulator, it would make it extremely laggy, so I uninstalled libiconv.

Pacman log doesn't show anything related to glibc being upgraded in the past few days, not sure why this suddenly started happening.

Thanks.

**Comment by wm4** [comment]
Can you post the build log? It's in ``build/config.log``.

**Comment by kevinlekiller** [comment]
Ah, I was pastebining the CLI output as you posted :) : http://pastebin.com/raw.php?i=ZRdq34Gk

Here's the `mpv/build/config.log`: http://sprunge.us/TdGd

**Comment by wm4** [comment]
Seems like libass.pc added this. Are you using libass git master as well?

**Comment by kevinlekiller** [comment]
Seems like it:

    [kevin@kevin-nuc libass]$ git branch && git rev-parse HEAD
    * (HEAD detached at origin/master)
      master
    e572a26d29ddff883880ef7b1c295acaa62a8a2f

**Comment by kevinlekiller** [comment]
The output of libass compilation if it helps: http://sprunge.us/ABNT

**Comment by wm4** [comment]
OK, I conclude the autoconfig check succeeds, even though it doesn't use the iconv lib requested by the script.

**Comment by kevinlekiller** [comment]
I edited the update script to checkout libass to https://github.com/libass/libass/commit/de4ea4bbd1c5101bf0b572a4facd58875845f495 which allowed the compilation to finish, not ideal but works for now.

**Comment by wm4** [comment]
Fixed in libass.

**Comment by kevinlekiller** [comment]
Confirmed, works, thanks.
