### ISSUE TITLE
error ./rebuild  on Powermac G5 /

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#69]
Hello ,

i used to build MPV on Wheezy (Debian 7) smoothly with this help here

https://nyxi.eu/blog/2014/01/19/compiling-mpv-in-Wheezy-2014/

Lately, i had problems, as with an PPC installation because the installer would require Harfbuzz that i am not able yet to compile on Debian Wheezy.
Could you please guide me through the process of Building MPV without Harfbuzz?

Thanks

**Comment by kevmitch** [comment]
The debian package no longer supports wheezy. Just use the generic build instructions.

**Comment by mrkapqa** [comment]
Thank you, do you mean these instructions here

https://github.com/mpv-player/mpv-build#instructions-for-debian-and-ubuntu

Will this work on Wheezy/Powerpc?

i remember that it uesed to work once, but lately i am always asked for 
this Harfbuzz thing.
Was not able to deactivate that via Flags neither; maybe you can pass by 
the correct Build phrase?

Rich

kevmitch schrieb:

**Comment by kevmitch** [comment]
No I mean the [Generic instuctions](https://github.com/mpv-player/mpv-build#generic-instructions). The ones you link will not work on wheezy because they require harfbuzz. The generic instructions only require the bare minimum of dependencies.

**Comment by kevmitch** [comment]
reopen if the generic instructions don't work.
