### ISSUE TITLE
Question re: ytdl & ffmpeg/libav binary

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv-build#70]
In Debian/Ubuntu packages mpv recommends youtube-dl package which then recommends ffmpeg | libav 
Generally speaking the packaged youtube-dl is semi-broken so for here don't recommend in packages but am curious if mpv's ytdl 'needs' either binary in some use cases of ytdl?

**Comment by wm4** [comment]
The mpv ytdl script doesn't need ffmpeg/libav CLI installed. But I heard youtube-dl itself can change behavior depending on whether ffmpeg/avconv is installed, which incorrectly affects mpv too. Don't know if they have yet acknowledged/solved this bug.
