### ISSUE TITLE
compilation error debian jessie x64

### ISSUE THREAD

**Issue by arigit2014** [mpv-player/mpv-build#71]
Hello and thanks for support mpv, i really enjoy it, but now i have some compilation error, the terminal show this:

237/237] Linking build/mpv
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status

I follow step by step the generic instructions and the debian instructions to build the .dep packages. 
both of them ended by that error. I check what kind of package is missing, but i really have no idea. 
no debian package with that name lEGL 
¿what is the missing dev file i need to install?

Thanks in advance.

**Comment by kevmitch** [comment]
the library is provided by ```libegl1-mesa-dev``` (or ```libegl1-nvidia``` with the non-free nvidia driver).

**Comment by arigit2014** [comment]
Ok, thank you very much :) i successfully build the glorious .deb packages...
...terminal show me this:

mpv --version
mpv 0.15.0-git-d1d6257 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Feb 11 07:38:56 ART 2016
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: n2.8.6

So, the job is done. Awesome. Im happy. Debian is great. You are great. Everything is great.
