### ISSUE TITLE
vapoursynth support not working?

### ISSUE THREAD

**Issue by kaefert** [mpv-player/mpv-build#73]
Hi there!

I've built & installed mpv using these helper scripts here on my freshly installed ubuntu mate 16.04 beta - like described in the readme:

```bash
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
echo --enable-libx264 >> ffmpeg_options
echo --enable-libmp3lame >> ffmpeg_options
echo --enable-libfdk-aac >> ffmpeg_options
echo --enable-nonfree >> ffmpeg_options
./update
rm -f mpv-build-deps_*_*.deb
mk-build-deps -s sudo -i
./rebuild -j4
dpkg-buildpackage -uc -us -b -j4
cd ..
dpkg -i mpv_*_amd64.deb
```

now first, the ./update script seems to call git in ways it doesn't like:
`fatal: git checkout: --detach does not take a path argument 'refs/tags/'`

and second although the build process seems to recognise vapoursynth as installed on my system:
```
Checking for VapourSynth filter bridge (Python)                           : yes 
Checking for VapourSynth filter bridge (Lazy Lua)                         : yes 
Checking for VapourSynth filter bridge (core)                             : yes 
```
it doesn't work as I am used to from previous installations:
```bash
$ mpv vapoursynth_test.vpy
Playing: vapoursynth_test.vpy
Failed to recognize file format.


Exiting... (Errors when loading file)
```

vapoursynth seems to work as it should when used with the vspipe utility:
```bash
PYTHONPATH=/usr/local/lib/python3.5/site-packages vspipe --y4m vapoursynth_test.vpy - | mpv -
```

I think I can remember that previously mpv needed to be built with the compiler switch `--with-vapoursynth` but this seems to have been replaced by autodetection since using this switch will throw an error instead of compiling.

I think on previous installs I've used the ppa from here: https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth
but sadly this repository does not have support for Ubuntu 16.04 xenial yet.

**Comment by wm4** [comment]
There's no support for "playing" vapoursynth python script, and likely never will be as it's a huge security risk to run random python code.

**Comment by kaefert** [comment]
hmm.. so I do remember wrongly that this previously worked?

**Comment by wm4** [comment]
It never worked this way.

>what is the extend of the vapoursynth support that is included in mpv right now?

There's a video filter.

**Comment by kaefert** [comment]
okey, thanks for the information.
