### ISSUE TITLE
Add option to disable OpenGL

### ISSUE THREAD

**Issue by 00SteinsGate00** [mpv-player/mpv-build#77]
Heyho,

I'm trying to compile MPV on Debian Jessie, since the version in the distro packages is 0.6, a little old.

This script (`rebuild`) works great so far, until it stops with because it can't find any OpenGL extensions and suggests `--disable-gl` to disable OpenGL support. If I give this option to the `rebuild` script however, it will pass it down to `make`, which doesn't recognize the option.

My application actually doesn't need any video output, only audio. It would be convenient to be able to just disable it.

**Comment by wm4** [comment]
You can create a file named `mpv_options` in the mpv-build directory and add mpv configure options to it (one per line).

**Comment by 00SteinsGate00** [comment]
Thank you!

**Comment by mrkapqa** [comment]
i am having problems with latest mpv-build master 0.26 as my thinkpad complains with libdrm atomic issue on debian wheezy 64-bit.
is it possible to use an older mpv-build eg. mpv 0.24 , where this problem did not occur?

thank you very much.
