### ISSUE TITLE
CentOS Installation Procedure

### ISSUE THREAD

**Issue by smacz42** [mpv-player/mpv-build#78]
Mpv is packeged on both arch and debian, so it's somewhat pointless to have "easy" installation instructions when the "easiest" would be to just use their respective repos.

Including the relevant repos would be awesome as well:

https://www.uncleninja.com/uncategorized/2016-05-04/install-mpv-player-smplayer-centos-7/

Is that worth of a separate issue?

**Comment by smacz42** [comment]
Also, when issuing `rebuild` on CentOS 6.8, `git` fails with:

```
+ git checkout --detach oring/master
error: unknown option `detach'
```

**Comment by kevmitch** [comment]
The only clearly identified problem here is that ancient versions of git lack `--detach`. What is the initial comment trying to say?

**Comment by smacz42** [comment]
@kevmitch, the python script also fails to download waf. It may be a version issue? (python --version returns 2.6.6) The below results in a successful download.

```
- print("String to {}...".format(WAFSTRING))
+ print("String to %s..." % (WAFSTRING))
```

**Comment by smacz42** [comment]
The initial comment may be disregarded. Issue is solved by: https://github.com/mpv-player/mpv-build/pull/79
