### ISSUE TITLE
differences debian and ubuntu - fast forward

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#80]
Hello ,

i tried several times to compile mpv on ubuntu 12.04 or lubuntu 12.04 or 14.04 . 
it would succeed to build but when i do fast forward a youtube-track via youtube-viewer it just stops suddenly.
When i build the with the same instructions on Debian Wheezy there is no problem; 
On jessie , there again is problem, there only way to circumvent FastForward/(bug) for me was to install Mpv via Deb-Multimedia.

here are the instructions i got for an older T61 with Nvidia (i think)

sudo aptitude install autoconf  automake  libasound2-dev libegl1-mesa-dev  libfontconfig-dev  libfreetype6-dev  libfribidi-dev libgl1-mesa-dev libgnutls-dev libtool libx11-dev libxext-dev libxinerama-dev libxrandr-dev  libxv-dev  pkg-config python  x11proto-core-dev yasm
./update
./clean
cd libass
git checkout 9a2b38e8f5957418362e86b525f72794565deedd
cd ..
./build -j2

**Comment by kevmitch** [comment]
What happens if you just use the view the video directly in mpv? What does the --log-file=log.txt say?

**Comment by mrkapqa** [comment]
sorry, i don't have ubuntu available atm;
whenever installing next time, i might tell you.
the above guidline that you gave me also onyl works for wheezy; on 
debian jessie , the fast-forward thing when compiling mpv-build also 
fails - but when i then add deb-multimedia and make sudo upgrade , it 
installs some new things, and mpv works as desired with fast-forward, eg 
withouth breaking playback of youtube-viewer.
thanks

Am 23.02.17 um 20:29 schrieb Kevin Mitchell:

**Comment by mrkapqa** [comment]
one strange thing is that when i use mpv-build(t) mpv on ubuntu, after  
evoking it through youtube-viewer - when i fast forward, the app mpv  
stops, and youtube-viewer is unusable, in fact, the whole terminal  
windows get unusable, eg. does no more react after initital breakup.
i do not know where to look for this log.txt , sorry. i still do not  
know how to search properly files on linux.

Zitat von Kevin Mitchell <notifications@github.com>:

**Comment by mrkapqa** [comment]
just built mpv on ubuntu 12.04 64bit. and this bug is still there.

Zitat von Kevin Mitchell <notifications@github.com>:

**Comment by kevmitch** [comment]
You need to reproduce the bug without youtube viewer so that we can tell what is actually going on. Play the youtube video by providing the url to mpv on the command line together with `--log-file=log.txt` and post the log.

**Comment by mrkapqa** [comment]
i had now same error with mpv-build on jessie 64bit , kde ,
this is the log

[   0.006][v][cplayer] Command line options: 'pressure - love conquer 
all.webm' '--log-file=log.txt'
[   0.006][v][cplayer] mpv git-eacf4a7 (C) 2000-2017 
mpv/MPlayer/mplayer2 projects
[   0.006][v][cplayer]  built on Fri Feb 24 21:18:23 CET 2017
[   0.006][v][cplayer] ffmpeg library versions:
[   0.006][v][cplayer]    libavutil       55.47.100
[   0.006][v][cplayer]    libavcodec      57.81.100
[   0.006][v][cplayer]    libavformat     57.66.102
[   0.006][v][cplayer]    libswscale      4.3.101
[   0.006][v][cplayer]    libavfilter     6.74.100
[   0.006][v][cplayer]    libswresample   2.4.100
[   0.006][v][cplayer] ffmpeg version: N-83644-g7025973
[   0.006][v][cplayer]
[   0.006][v][cplayer] Configuration: ./waf configure
[   0.006][v][cplayer] List of enabled features: alsa any-gl asm atomics 
audio-input build-date c11-tls cplayer cuda-hwaccel debug-build dlopen 
drm dvbin egl-helpers egl-x11 encoding fchmod gcc-tls gl gl-x11 
glibc-thread-name glob gnuc iconv is_ffmpeg libass libass-osd libav 
libavcodec libavdevice libdl libm librt linux-fstatfs nanosleep optimize 
oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads shm 
standard-gl stdatomic subprocess termios tv tv-v4l2 videodev vt.h x11 
xext xinerama xrandr xv zlib
[   0.006][v][cplayer] Setting option 'log-file' = 'log.txt' (flags = 8)
[   0.008][v][global] user path: 'log.txt' -> 'log.txt'
[   0.008][v][global] config path: 'scripts' -/-> 
'/home/rich/.config/mpv/scripts'
[   0.008][v][global] config path: 'scripts' -/-> '/home/rich/.mpv/scripts'
[   0.008][v][global] config path: 'scripts' -/-> 
'/usr/local/etc/mpv/scripts'
[   0.008][v][global] config path: 'watch_later' -> 
'/home/rich/.config/mpv/watch_later'
[   0.008][i][cplayer] Playing: pressure - love conquer all.webm
[   0.008][v][file] Opening pressure - love conquer all.webm
[   0.008][v][file] Stream opened successfully.
[   0.009][v][demux] Trying demuxers for level=normal.
[   0.013][v][mkv] Found the head...
[   0.013][v][mkv] + a segment...
[   0.013][v][mkv] Parsing seek head...
[   0.013][v][mkv] |+ segment information...
[   0.013][v][mkv] | + muxing app: google
[   0.013][v][mkv] | + writing app: google
[   0.013][v][mkv] | + timecode scale: 1000000
[   0.013][v][mkv] | + duration: 231.164s
[   0.013][v][mkv] |+ segment tracks...
[   0.013][v][mkv] | + a track...
[   0.013][v][mkv] |  + Track number: 1
[   0.013][v][mkv] |  + Track type: Video
[   0.013][v][mkv] |  + Video track
[   0.013][v][mkv] |   + Pixel width: 540
[   0.013][v][mkv] |   + Pixel height: 360
[   0.013][v][mkv] |  + Codec ID: V_VP8
[   0.013][v][mkv] |  + Language: und
[   0.013][v][mkv] |  + Default duration: 33.367ms ( = 29.970 fps)
[   0.013][v][mkv] | + a track...
[   0.013][v][mkv] |  + Track number: 2
[   0.013][v][mkv] |  + Track type: Audio
[   0.013][v][mkv] |  + Audio track
[   0.013][v][mkv] |   + Sampling frequency: 44100.000000
[   0.013][v][mkv] |   + Bit depth: 16
[   0.013][v][mkv] |   + Channels: 2
[   0.013][v][mkv] |  + Codec ID: A_VORBIS
[   0.013][v][mkv] |  + CodecPrivate, length 3845
[   0.013][v][mkv] |  + Language: und
[   0.013][v][mkv] |+ found cluster
[   0.013][v][mkv] Deferring reading cues.
[   0.013][v][mkv] All headers are parsed!
[   0.013][v][demux] Detected file format: Matroska
[   0.014][v][cplayer] Opening done: pressure - love conquer all.webm
[   0.014][v][find_files] Loading external files in .
[   0.014][v][global] config path: 'sub/' -/-> '/home/rich/.config/mpv/sub/'
[   0.014][v][global] config path: 'sub/' -/-> '/home/rich/.mpv/sub/'
[   0.014][v][global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'
[   0.014][v][global] config path: 'audio/' -/-> 
'/home/rich/.config/mpv/audio/'
[   0.014][v][global] config path: 'audio/' -/-> '/home/rich/.mpv/audio/'
[   0.014][v][global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'
[   0.014][i][cplayer]  (+) Video --vid=1 (*) (vp8)
[   0.014][i][cplayer]  (+) Audio --aid=1 (*) (vorbis)
[   0.014][v][vo/opengl] Initializing OpenGL backend 'x11probe'
[   0.014][v][vo/opengl/x11] X11 opening display: :0
[   0.019][v][vo/opengl/x11] X11 running at 1440x900 (":0" => local display)
[   0.019][v][vo/opengl/x11] Detected wm supports NetWM.
[   0.019][v][vo/opengl/x11] Detected wm supports FULLSCREEN state.
[   0.019][v][vo/opengl/x11] Detected wm supports ABOVE state.
[   0.019][v][vo/opengl/x11] Detected wm supports BELOW state.
[   0.019][v][vo/opengl/x11] Detected wm supports STAYS_ON_TOP state.
[   0.020][v][vo/opengl/x11] Display 0 (LVDS1): [0, 0, 1440, 900] @ 
59.995824 FPS
[   0.020][v][vo/opengl/x11] Current display FPS: 59.995824
[   0.035][v][vo/opengl] GLX chose FB config with ID 0x6c
[   0.035][v][vo/opengl] GLX chose visual with ID 0x80
[   0.037][v][vo/opengl] Creating OpenGL 3.3 context...
[   0.038][v][vo/opengl/x11] X11 error: GLXBadFBConfig
[   0.038][v][vo/opengl/x11] Type: 0, display: 0x7ff5c40227a0, 
resourceid: 152, serial: 45
[   0.038][v][vo/opengl/x11] Error code: b5, request code: 9c, minor 
code: 22
[   0.038][v][vo/opengl] Creating OpenGL 3.2 context...
[   0.038][v][vo/opengl/x11] X11 error: GLXBadFBConfig
[   0.038][v][vo/opengl/x11] Type: 0, display: 0x7ff5c40227a0, 
resourceid: 152, serial: 48
[   0.038][v][vo/opengl/x11] Error code: b5, request code: 9c, minor 
code: 22
[   0.038][v][vo/opengl] Creating OpenGL 3.1 context...
[   0.038][v][vo/opengl/x11] X11 error: GLXBadFBConfig
[   0.038][v][vo/opengl/x11] Type: 0, display: 0x7ff5c40227a0, 
resourceid: 152, serial: 4b
[   0.038][v][vo/opengl/x11] Error code: b5, request code: 9c, minor 
code: 22
[   0.038][v][vo/opengl] Creating OpenGL 3.0 context...
[   0.038][v][vo/opengl/x11] X11 error: GLXBadFBConfig
[   0.038][v][vo/opengl/x11] Type: 0, display: 0x7ff5c40227a0, 
resourceid: 152, serial: 4e
[   0.038][v][vo/opengl/x11] Error code: b5, request code: 9c, minor 
code: 22
[   0.038][v][vo/opengl] Creating OpenGL 2.1 context...
[   0.049][v][vo/opengl] GL_VERSION='2.1 Mesa 10.3.2'
[   0.049][v][vo/opengl] Detected desktop OpenGL 2.1.
[   0.049][v][vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[   0.049][v][vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Ironlake Mobile '
[   0.049][v][vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[   0.049][v][vo/opengl] Loaded extension GL_ARB_map_buffer_range.
[   0.050][v][vo/opengl] Loaded extension GL_ARB_framebuffer_object.
[   0.050][v][vo/opengl] Loaded extension GL_ARB_vertex_array_object.
[   0.050][v][vo/opengl] Loaded extension GL_ARB_texture_rg.
[   0.050][v][vo/opengl] Loaded extension GL_ARB_texture_float.
[   0.050][v][vo/opengl] Loaded extension GL_ARB_sync.
[   0.050][v][vo/opengl] Loaded extension GLX_SGI_swap_control.
[   0.050][v][vo/opengl] Loaded extension GLX_SGI_video_sync.
[   0.050][v][vo/opengl] Loaded extension GL_ARB_debug_output.
[   0.050][v][vo/opengl] No vdpau support found - probing more things.
[   0.050][v][vo/opengl/x11] uninit ...
[   0.051][v][vo/opengl] Initializing OpenGL backend 'x11egl'
[   0.051][v][vo/opengl/x11] X11 opening display: :0
[   0.053][v][vo/opengl/x11] X11 running at 1440x900 (":0" => local display)
[   0.054][v][vo/opengl/x11] Detected wm supports NetWM.
[   0.054][v][vo/opengl/x11] Detected wm supports FULLSCREEN state.
[   0.054][v][vo/opengl/x11] Detected wm supports ABOVE state.
[   0.054][v][vo/opengl/x11] Detected wm supports BELOW state.
[   0.054][v][vo/opengl/x11] Detected wm supports STAYS_ON_TOP state.
[   0.054][v][vo/opengl/x11] Display 0 (LVDS1): [0, 0, 1440, 900] @ 
59.995824 FPS
[   0.054][v][vo/opengl/x11] Current display FPS: 59.995824
[   0.069][v][vo/opengl] EGL_VERSION=1.4 (DRI2)
[   0.069][v][vo/opengl] EGL_VENDOR=Mesa Project
[   0.069][v][vo/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES OpenGL_ES2
[   0.069][v][vo/opengl] Trying to create Desktop OpenGL context.
[   0.071][v][vo/opengl] chose visual 0x21
[   0.073][v][vo/opengl] GL_VERSION='2.1 Mesa 10.3.2'
[   0.073][v][vo/opengl] Detected desktop OpenGL 2.1.
[   0.073][v][vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[   0.073][v][vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Ironlake Mobile '
[   0.073][v][vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[   0.073][v][vo/opengl] Loaded extension GL_ARB_map_buffer_range.
[   0.073][v][vo/opengl] Loaded extension GL_ARB_framebuffer_object.
[   0.073][v][vo/opengl] Loaded extension GL_ARB_vertex_array_object.
[   0.073][v][vo/opengl] Loaded extension GL_ARB_texture_rg.
[   0.073][v][vo/opengl] Loaded extension GL_ARB_texture_float.
[   0.073][v][vo/opengl] Loaded extension GL_ARB_sync.
[   0.073][v][vo/opengl] Loaded extension GL_ARB_debug_output.
[   0.073][v][vo/opengl] swap_control extension missing.
[   0.074][v][vo/opengl] 16 bit texture depth: 16.
[   0.074][v][vo/opengl] Reported display depth: R=8, G=8, B=8
[   0.074][v][vo/opengl] Testing FBO format 0x805b
[   0.074][v][vo/opengl] Create FBO: 16x16 (16x16)
[   0.074][v][vo/opengl] Using FBO format 0x805b.
[   0.074][v][vo/opengl] No advanced processing required. Enabling dumb 
mode.
[   0.075][v][vo/opengl] Assuming 59.995824 FPS for display sync.
[   0.075][v][vd] Container reported FPS: 29.969999
[   0.075][v][vd] Codec list:
[   0.075][v][vd]     vp8 - On2 VP8
[   0.075][v][vd]     vp8_cuvid (vp8) - Nvidia CUVID VP8 decoder
[   0.075][v][vd] Opening video decoder vp8
[   0.075][v][vd] Not trying to use hardware decoding: codec vp8 is not 
on whitelist, or does not support hardware acceleration.
[   0.075][v][vd] Using software decoding.
[   0.075][v][vd] Detected 4 logical cores.
[   0.075][v][vd] Requesting 5 threads for decoding.
[   0.075][v][vd] Selected video codec: vp8 (On2 VP8)
[   0.076][v][ad] Codec list:
[   0.076][v][ad]     vorbis - Vorbis
[   0.076][v][ad] Opening audio decoder vorbis
[   0.076][v][ad] Requesting 1 threads for decoding.
[   0.077][v][ad] Selected audio codec: vorbis (Vorbis)
[   0.077][v][cplayer] Starting playback...
[   0.077][v][vo/opengl/x11] Disabling screensaver.
[   0.079][v][af] Audio filter chain:
[   0.079][v][af]   [in] 44100Hz stereo 2ch floatp
[   0.079][v][af]   [out] 44100Hz stereo 2ch floatp
[   0.079][v][af]   [ao] 44100Hz stereo 2ch floatp
[   0.079][v][ao] Trying audio driver 'alsa'
[   0.079][v][ao/alsa] requested format: 44100 Hz, stereo channels, floatp
[   0.079][v][ao/alsa] using ALSA version: 1.0.28
[   0.079][v][ao/alsa] opening device 'default'
[   0.094][v][ao/alsa] trying format float
[   0.094][v][ao/alsa] Going to set final HW params:
[   0.094][v][ao/alsa] ---
[   0.094][v][ao/alsa] ACCESS:  RW_INTERLEAVED
[   0.094][v][ao/alsa] FORMAT:  FLOAT_LE
[   0.094][v][ao/alsa] SUBFORMAT:  STD
[   0.094][v][ao/alsa] SAMPLE_BITS: 32
[   0.094][v][ao/alsa] FRAME_BITS: 64
[   0.094][v][ao/alsa] CHANNELS: 2
[   0.094][v][ao/alsa] RATE: 44100
[   0.094][v][ao/alsa] PERIOD_TIME: (15623 15647)
[   0.094][v][ao/alsa] PERIOD_SIZE: (689 690)
[   0.094][v][ao/alsa] PERIOD_BYTES: (5512 5513)
[   0.094][v][ao/alsa] PERIODS: 16
[   0.094][v][ao/alsa] BUFFER_TIME: 250000
[   0.094][v][ao/alsa] BUFFER_SIZE: 11025
[   0.094][v][ao/alsa] BUFFER_BYTES: 88200
[   0.094][v][ao/alsa] TICK_TIME: ALL
[   0.094][v][ao/alsa] ---
[   0.114][v][ao/alsa] hw pausing supported: yes
[   0.114][v][ao/alsa] buffersize: 11025 samples
[   0.114][v][ao/alsa] period size: 689 samples
[   0.114][v][ao/alsa] device buffer: 11025 samples.
[   0.114][v][ao/alsa] using soft-buffer of 11025 samples.
[   0.115][i][cplayer] AO: [alsa] 44100Hz stereo 2ch float
[   0.115][v][cplayer] AO: Description: ALSA audio output
[   0.115][v][af] Adding filter lavrresample
[   0.115][v][af] Audio filter chain:
[   0.115][v][af]   [in] 44100Hz stereo 2ch floatp
[   0.115][v][af]   [lavrresample] 44100Hz stereo 2ch float [a]
[   0.115][v][af]   [out] 44100Hz stereo 2ch float
[   0.115][v][af]   [ao] 44100Hz stereo 2ch float
[   0.122][v][vd] Decoder format: 540x360 [0:1] yuv420p 
bt.601/auto/auto/limited CL=unknown
[   0.122][v][vd] Using container aspect ratio.
[   0.122][v][vf] Video filter chain:
[   0.122][v][vf]   [in] 540x360 yuv420p bt.601/bt.709/bt.1886/limited 
CL=unknown
[   0.122][v][vf]   [out] 540x360 yuv420p bt.601/bt.709/bt.1886/limited 
CL=unknown
[   0.122][i][cplayer] VO: [opengl] 540x360 yuv420p
[   0.122][v][cplayer] VO: Description: Extended OpenGL Renderer
[   0.146][v][vo/opengl] Resize: 540x360
[   0.146][v][vo/opengl] Window size: 540x360
[   0.146][v][vo/opengl] Video source: 540x360 (1:1)
[   0.146][v][vo/opengl] Video display: (0, 0) 540x360 -> (0, 0) 540x360
[   0.146][v][vo/opengl] Video scale: 1.000000/1.000000
[   0.146][v][vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[   0.146][v][vo/opengl] Video borders: l=0 t=0 r=0 b=0
[   0.146][v][vo/opengl] Testing FBO format 0x805b
[   0.146][v][vo/opengl] Create FBO: 16x16 (16x16)
[   0.146][v][vo/opengl] Using FBO format 0x805b.
[   0.146][v][vo/opengl] No advanced processing required. Enabling dumb 
mode.
[   0.146][v][vo/opengl] Texture for plane 0: 540x360
[   0.146][v][vo/opengl] Texture for plane 1: 270x180
[   0.146][v][vo/opengl] Texture for plane 2: 270x180
[   0.146][v][cplayer] set video colors output-levels=0
[   0.158][v][vo/opengl] recompiling a shader program:
[   0.158][v][vo/opengl] [  1] color.r = 1.000000 * 
vec4(texture(texture0, texcoord0)).r;
[   0.158][v][vo/opengl] [  2] color.g = 1.000000 * 
vec4(texture(texture1, texcoord1)).r;
[   0.158][v][vo/opengl] [  3] color.b = 1.000000 * 
vec4(texture(texture2, texcoord2)).r;
[   0.158][v][vo/opengl] [  4] // color conversion
[   0.158][v][vo/opengl] [  5] color = color.rgba;
[   0.158][v][vo/opengl] [  6] color.rgb = mat3(colormatrix) * color.rgb 
+ colormatrix_c;
[   0.158][v][vo/opengl] [  7] color.a = 1.0;
[   0.158][v][vo/opengl] [  8] // color mapping
[   0.170][v][cplayer] first video frame after restart shown
[   0.170][v][cplayer] starting audio playback
[   0.170][v][cplayer] playback restart complete
[   2.499][v][cplayer] Run command: seek, flags=9, args=[5.000000, 
relative, unused]
[   2.499][v][mkv] queuing seek to 7.369000
[   2.499][v][mkv] execute seek (to 7.369000 flags 4)
[   2.499][v][mkv] Seeking to 4469027 to read header element 0x1c53bb6b.
[   2.499][v][mkv] Parsing cues...
[   2.499][v][mkv] seek done
[   2.511][v][vd] Decoder format: 540x360 [0:1] yuv420p 
bt.601/auto/auto/limited CL=unknown
[   2.511][v][vd] Using container aspect ratio.
[   2.515][v][global] config path: 'fonts' -/-> 
'/home/rich/.config/mpv/fonts'
[   2.515][v][global] config path: 'fonts' -/-> '/home/rich/.mpv/fonts'
[   2.515][v][global] config path: 'fonts' -/-> '/usr/local/etc/mpv/fonts'
[   2.515][v][osd/libass] Shaper: FriBidi 0.19.6 (SIMPLE)
[   2.515][v][global] config path: 'subfont.ttf' -/-> 
'/home/rich/.config/mpv/subfont.ttf'
[   2.515][v][global] config path: 'subfont.ttf' -/-> 
'/home/rich/.mpv/subfont.ttf'
[   2.515][v][global] config path: 'subfont.ttf' -/-> 
'/usr/local/etc/mpv/subfont.ttf'
[   2.515][v][global] config path: 'fonts.conf' -/-> 
'/home/rich/.config/mpv/fonts.conf'
[   2.515][v][global] config path: 'fonts.conf' -/-> 
'/home/rich/.mpv/fonts.conf'
[   2.515][v][global] config path: 'fonts.conf' -/-> 
'/usr/local/etc/mpv/fonts.conf'
[   2.515][v][osd/libass] Setting up fonts...

**Comment by mrkapqa** [comment]
problem has been solved now by

sudo rm -r encoding-profiles.conf

now i just have to get youtube-viewer working on jessie with mpv. it 
appears in contrast to wheezy it doesnet open video.

**Comment by kevmitch** [comment]
> sudo rm -r encoding-profiles.conf

This should have nothing to do with playback.

The above log looks like it was cut off. Was there more to it? Was it captured when the bug happened?

> X11 error: GLXBadFBConfig

This sounds bad, although I'm not sure if it's related to your issue.

**Comment by mrkapqa** [comment]
Thank you Kevin,

i had built the mpv-player with your instructions that kept hold of 
libass for suiting wheezy. now on jessie this did not funtion anymore, 
somehow.
built then mpv according to these here

https://nyxi.eu/compiling-mpv-on-debian.html#compiling-mpv-on-debian

that helped me to get working mpv copy on jessie.

afterwards installed youtube-viewer 3.2.5, now fully functional, with 
fast-rewind, no problem anymore :)

**Comment by kevmitch** [comment]
ok, glad it works
