### ISSUE TITLE
Clonning fribidi via HTTP isn't working

### ISSUE THREAD

**Issue by alcos0** [mpv-player/mpv-build#82]
Hi! For some reason cloning fribidi via HTTP isn't working for me. I already tried different machines and different networks, but the issue persists.
```
+ test -e fribidi
+ git clone http://anongit.freedesktop.org/git/fribidi/fribidi.git fribidi
Cloning into 'fribidi'...
fatal: unable to access 'http://anongit.freedesktop.org/git/fribidi/fribidi.git/': Failed to connect to anongit.freedesktop.org port 80: Network is unreachable
```
And I have no issues accessing http://anongit.freedesktop.org/git/fribidi/fribidi.git/ through browser. Changing "http://anongit.freedesktop.org/git/fribidi/fribidi.git/" to "git://anongit.freedesktop.org/git/fribidi/fribidi.git/" works fine though. Anyone having the same issue?

**Comment by wm4** [comment]
So I disabled fribidi fetching. I'm assuming you didn't want it anyway, meaning you didn't uncomment the lines that actually build it.
