### ISSUE TITLE
FFMpeg not found - RPi

### ISSUE THREAD

**Issue by Maigre** [mpv-player/mpv-build#83]
Hi,
when ./rebuild -j4 libass and ffmpeg are compiled correctly
but once it reach the mpv-config, this one fails, stating that it can't find ffmpeg:

> Unable to find development files for some of the required FFmpeg/Libav libraries. You need at least FFmpeg 3.2.2 or Libav 12. Aborting.

FFmpeg is properly compiled and available in mpv-build/ffmpeg_build
Headers seems available in mpv-build/build_libs/include/
Binaries are in mpv-build/build_libs/bin/
and .a are found in mpv-build/build_libs/lib/

so i don't understand why mpv-config fail to find it.. is there a path trick or something ?
Thanks !

**Comment by Maigre** [comment]
The weird thing is 

Checking for FFmpeg/Libav present                                    : yes 
Checking for libav* is FFmpeg                                        : no 
Checking for libav* is Libav                                         : no 
Checking for Libav/FFmpeg library versions                           : not found any of is_ffmpeg, is_libav

**Comment by wm4** [comment]
No, the script shouldn't fail here. Upload `mpv/build/config.log`.

**Comment by Maigre** [comment]
https://pastebin.com/7zWsW8aQ

**Comment by wm4** [comment]
The build log says it couldn't link to the RPI specific libs (mmal etc.) because they were not found. That's why last ffmpeg/libav test fails.

**Comment by Maigre** [comment]
both test are failing to compile. 
The first one (is_FFMpeg) fails because missing -lmmal_core -lmmal_util -lmmal_vc_client -lbcm_host (related to the other issue i created i guess)

The second one because ../test.c:3:7: error: size of array ‘x’ is negative
 { int x[LIBAVCODEC_VERSION_MICRO >= 100 ? -1 : 1]; return 0; }
which is weird..

**Comment by Maigre** [comment]
ldconfig -p | grep libmmal
	libmmal_vc_client.so (libc6,hard-float) => /opt/vc/lib/libmmal_vc_client.so
	libmmal_util.so (libc6,hard-float) => /opt/vc/lib/libmmal_util.so
	libmmal_core.so (libc6,hard-float) => /opt/vc/lib/libmmal_core.so
	libmmal_components.so (libc6,hard-float) => /opt/vc/lib/libmmal_components.so
	libmmal.so (libc6,hard-float) => /opt/vc/lib/libmmal.so

ldconfig -p | grep bcm
	libbcm_host.so (libc6,hard-float) => /opt/vc/lib/libbcm_host.so

so every libs are here already, 
and ffmpeg did not have problem to compile with mmal enabled..

same issue as #84 

any clue why it could be broken here ?

**Comment by Maigre** [comment]
same as #84, 
to fix this just run 

`export LIBRARY_PATH=/opt/vc/lib`

Best,
