### ISSUE TITLE
Raspberry Pi support broken

### ISSUE THREAD

**Issue by Maigre** [mpv-player/mpv-build#84]
Hi,
while running mpv-config, once i reach the Raspberry pi support test, it fails stating 

> no ('bcm_host' not found)

I am running on Rpi 2 with the last (April 17) Raspbian jessie.
I digged a bit and saw that /opt/vc/lib/pkgconfig was missing.
I ran rpi-update which updated the firmware, and now /opt/vc/lib/pkgconfig is available.
But it still fails in mpv-config, with the same ('bcm_host' not found) error.
Any clue ?
Thanks !

**Comment by Maigre** [comment]
In the waf test (custom.py => check_rpi), the 2 lines failing are:

check_pkg_config('bcm_host', uselib_store='bcm_host')
and
check_cc(lib=['mmal_core', 'mmal_util', 'mmal_vc_client'], use=['bcm_host'])

the filter use ['/opt/vc/lib/pkgconfig', '/home/pi/mpv-build/build_libs/lib/pkgconfig']
both are valid directories, the first one contains
bcm_host.pc  brcmegl.pc  brcmglesv2.pc  brcmvg.pc  egl.pc  glesv2.pc  mmal.pc  vcsm.pc  vg.pc

so i don't understand why check_pkg_config('bcm_host', uselib_store='bcm_host') fails..
Any clue ?
Thanks !

**Comment by wm4** [comment]
Raspbian is probably randomly broken/unsupported by now. Might require manual hacks by the user to get it to work.

**Comment by Maigre** [comment]
hmm ok, sad news.
i'll continue to invastigate but i am not ultra saavy on these kind of issue..

**Comment by Maigre** [comment]
ok i fixed this first issue.
on recent Raspbian jessie, you have to:

* run RPi-update, to obtain /opt/vc/lib/pkgconfig
`sudo apt install rpi-update
sudo rpi-update
sudo reboot`

* add /opt/vc/lib/pkgconfig/ to PKG_CONFIG_PATH before running mpv-build
`export PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig/`

now the Raspberry test pass !
