### ISSUE TITLE
RPI PKG_CONFIG doesn't include EGL 

### ISSUE THREAD

**Issue by ClashTheBunny** [mpv-player/mpv-build#88]
I had trouble setting the INCLUDES/-I option on the raspberry pi to get it to compile.  I ended up cloning a fake pkg_config directory for the rpi from https://gist.github.com/00530de711ac75fdb528.git into /opt/vc/lib/pkgconfig/ and doing an 

```export PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig/```

It built with that.  Is there a better way of setting INCLUDES for a package that doesn't have pkgconfig info?  Is that workaround probably the best option?

**Comment by wm4** [comment]
If your distro doesn't provide .pc files for those, this is probably the best you can do.

**Comment by wm4** [comment]
We stopped using .pc for RPI because of issues.
