### ISSUE TITLE
./build -j2 - error - : cannot find -lEGL

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv-build#90]
hello ,

i succesully built mpv on debian 7.7 i386 some day ago;

today i tried again, but this time i had the laptop updated with nvidia-legacy-drivers as shown in the official wiki (nvidia driver 340.xxx)

when doing

./build -j2 

get the following erro

[226/226] Linking build/mpv
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status

thanks

**Comment by kevmitch** [comment]
This is provided by the `libegl1` package. make sure you have that installed.

**Comment by klopsi** [comment]
[224/224] Linking build/mpv
/usr/bin/ld: cannot find -lEGL
/usr/bin/ld: cannot find -lEGL
libegl1 is already the newest version (1.0.0-2ubuntu2.2)
hewp

**Comment by lachs0r** [comment]
You need the -dev package.
