### ISSUE TITLE
Unable to find development files for some of the required FFmpeg/Libav libraries.

### ISSUE THREAD

**Issue by geezuh** [mpv-player/mpv-build#98]
All the libraries should be installed with ./rebuild correct?

http://termbin.com/2bi5

`LD      ffserver_g
STRIP   ffserver
INSTALL install-progs-yes
INSTALL ffmpeg
INSTALL ffprobe
INSTALL ffserver
INSTALL home/pi/src/mpv-build/ffmpeg/presets/libvpx-1080p50_60.ffpreset
INSTALL home/pi/src/mpv-build/ffmpeg/presets/libvpx-360p.ffpreset
INSTALL home/pi/src/mpv-build/ffmpeg/presets/libvpx-1080p.ffpreset
INSTALL home/pi/src/mpv-build/ffmpeg/presets/libvpx-720p50_60.ffpreset
INSTALL home/pi/src/mpv-build/ffmpeg/presets/libvpx-720p.ffpreset
INSTALL home/pi/src/mpv-build/ffmpeg/doc/ffprobe.xsd
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/transcoding.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/demuxing_decoding.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/filtering_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/muxing.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/avio_dir_cmd.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/encode_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/hw_decode.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/filter_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/http_multiclient.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/resampling_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/decode_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/metadata.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/remuxing.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/filtering_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/extract_mvs.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/avio_reading.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/qsvdec.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/vaapi_encode.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/decode_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/transcode_aac.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/encode_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/scaling_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/README
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/Makefile
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/transcoding.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/demuxing_decoding.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/filtering_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/muxing.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/avio_dir_cmd.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/encode_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/hw_decode.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/filter_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/http_multiclient.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/resampling_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/decode_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/metadata.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/remuxing.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/filtering_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/extract_mvs.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/avio_reading.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/qsvdec.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/vaapi_encode.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/decode_audio.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/transcode_aac.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/encode_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/scaling_video.c
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/README
INSTALL home/pi/src/mpv-build/ffmpeg/doc/examples/Makefile
INSTALL libavdevice/libavdevice.a
INSTALL libavfilter/libavfilter.a
INSTALL libavformat/libavformat.a
INSTALL libavcodec/libavcodec.a
INSTALL libpostproc/libpostproc.a
INSTALL libswresample/libswresample.a
INSTALL libswscale/libswscale.a
INSTALL libavutil/libavutil.a
INSTALL home/pi/src/mpv-build/ffmpeg/libavdevice/avdevice.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavdevice/version.h
GEN     libavdevice/libavdevice.pc
INSTALL libavdevice/libavdevice.pc
INSTALL home/pi/src/mpv-build/ffmpeg/libavfilter/avfilter.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavfilter/buffersink.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavfilter/buffersrc.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavfilter/version.h
GEN     libavfilter/libavfilter.pc
INSTALL libavfilter/libavfilter.pc
INSTALL home/pi/src/mpv-build/ffmpeg/libavformat/avformat.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavformat/avio.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavformat/version.h
GEN     libavformat/libavformat.pc
INSTALL libavformat/libavformat.pc
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/ac3_parser.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/adts_parser.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/avcodec.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/avdct.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/avfft.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/d3d11va.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/dirac.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/dv_profile.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/dxva2.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/jni.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/mediacodec.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/qsv.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/vaapi.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/vdpau.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/version.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/videotoolbox.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/vorbis_parser.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavcodec/xvmc.h
GEN     libavcodec/libavcodec.pc
INSTALL libavcodec/libavcodec.pc
INSTALL home/pi/src/mpv-build/ffmpeg/libpostproc/postprocess.h
INSTALL home/pi/src/mpv-build/ffmpeg/libpostproc/version.h
GEN     libpostproc/libpostproc.pc
INSTALL libpostproc/libpostproc.pc
INSTALL home/pi/src/mpv-build/ffmpeg/libswresample/swresample.h
INSTALL home/pi/src/mpv-build/ffmpeg/libswresample/version.h
GEN     libswresample/libswresample.pc
INSTALL libswresample/libswresample.pc
INSTALL home/pi/src/mpv-build/ffmpeg/libswscale/swscale.h
INSTALL home/pi/src/mpv-build/ffmpeg/libswscale/version.h
GEN     libswscale/libswscale.pc
INSTALL libswscale/libswscale.pc
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/adler32.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/aes.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/aes_ctr.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/attributes.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/audio_fifo.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/avassert.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/avstring.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/avutil.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/base64.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/blowfish.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/bprint.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/bswap.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/buffer.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/cast5.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/camellia.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/channel_layout.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/common.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/cpu.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/crc.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/des.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/dict.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/display.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/downmix_info.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/error.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/eval.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/fifo.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/file.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/frame.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hash.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hmac.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_cuda.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_d3d11va.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_drm.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_dxva2.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_qsv.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_vaapi.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_videotoolbox.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/hwcontext_vdpau.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/imgutils.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/intfloat.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/intreadwrite.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/lfg.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/log.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/macros.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/mathematics.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/mastering_display_metadata.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/md5.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/mem.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/motion_vector.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/murmur3.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/opt.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/parseutils.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/pixdesc.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/pixelutils.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/pixfmt.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/random_seed.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/rc4.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/rational.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/replaygain.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/ripemd.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/samplefmt.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/sha.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/sha512.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/spherical.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/stereo3d.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/threadmessage.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/time.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/timecode.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/timestamp.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/tree.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/twofish.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/version.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/xtea.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/tea.h
INSTALL home/pi/src/mpv-build/ffmpeg/libavutil/lzo.h
INSTALL libavutil/avconfig.h
INSTALL libavutil/ffversion.h
GEN     libavutil/libavutil.pc
INSTALL libavutil/libavutil.pc
make: Leaving directory '/home/pi/src/mpv-build/ffmpeg_build'
Using mpv options:
Setting top to                           : /home/pi/src/mpv-build/mpv
Setting out to                           : /home/pi/src/mpv-build/mpv/build
Checking for waf version in 1.8.4-2.0.0  : ok
Checking for program 'cc'                : /usr/bin/cc
Checking for program 'pkg-config'        : /usr/bin/pkg-config
Checking for program 'ar'                : /usr/bin/ar
Checking for program 'rst2html'          : not found
Checking for program 'rst2man'           : not found
Checking for program 'rst2pdf'           : not found
Checking for program 'windres'           : not found
Checking for program 'perl'              : /usr/bin/perl
Checking for 'gcc' (C compiler)          : /usr/bin/cc
Detected target OS:                      : os-linux
Checking for compiler flags -Werror=implicit-function-declaration : yes
Checking for compiler flags -Wno-error=deprecated-declarations    : yes
Checking for compiler flags -Wno-error=unused-function            : yes
Checking for compiler flags -Wempty-body                          : yes
Checking for compiler flags -Wdisabled-optimization               : yes
Checking for compiler flags -Wstrict-prototypes                   : yes
Checking for compiler flags -Wno-format-zero-length               : yes
Checking for compiler flags -Werror=format-security               : yes
Checking for compiler flags -Wno-redundant-decls                  : yes
Checking for compiler flags -Wvla                                 : yes
Checking for mpv CLI player                                       : yes
Checking for shared library                                       : disabled
Checking for static library                                       : disabled
Checking for static build                                         : disabled
Checking for whether to include binary compile time               : yes
Checking for whether to optimize                                  : yes
Checking for whether to compile-in debugging information          : yes
Checking for manpage generation                                   : no (missing RST2MAN)
Checking for html manual generation                               : disabled
Checking for pdf manual generation                                : disabled
Checking for dynamic loader                                       : yes
Checking for C plugins                                            : yes
Checking for zsh completion                                       : disabled
Checking for inline assembly (currently without effect)           : yes
Checking for test suite (using cmocka)                            : disabled
Checking for generate a clang compilation database                : disabled
Checking for compiler support for noexecstack                     : yes
Checking for linker support for --nxcompat --no-seh --dynamicbase : no
Checking for -lm                                                  : yes
Checking for MinGW                                                : os-win32 not found
Checking for POSIX environment                                    : yes
Checking for Android environment                                  : no
Checking for development environment                              : yes
Checking for Universal Windows Platform                           : disabled
Checking for win32 desktop APIs                                   : not found any of os-win32, os-cygwin
Checking for internal pthread wrapper for win32 (Vista+)          : os-win32 not found
Checking for POSIX threads                                        : yes
Checking for GNU C extensions                                     : yes
Checking for stdatomic.h                                          : yes
Checking for stdatomic.h support or slow emulation                : yes
Checking for linking with -lrt                                    : yes
Checking for iconv                                                : yes
Checking for w32/dos paths                                        : not found any of os-win32, os-cygwin
Checking for termios                                              : yes
Checking for shm                                                  : yes
Checking for nanosleep                                            : yes
Checking for POSIX spawnp()/kill()                                : yes
Checking for Windows pipe support                                 : win32-desktop not found
Checking for glob() POSIX support                                 : yes
Checking for glob() win32 replacement                             : not found any of os-win32, os-cygwin
Checking for any glob() support                                   : yes
Checking for fchmod()                                             : yes
Checking for vt.h                                                 : yes
Checking for gbm.h                                                : no
Checking for GLIBC API for setting thread name                    : yes
Checking for OSX API for setting thread name                      : glibc-thread-name found
Checking for BSD API for setting thread name                      : glibc-thread-name found
Checking for BSD's fstatfs()                                      : no
Checking for Linux's fstatfs()                                    : yes
Checking for Samba support (makes mpv GPLv3)                      : disabled
Checking for Lua                                                  : yes (version found: luajit)
Checking for Javascript (MuJS backend)                            : no ('mujs >= 1.0.0' not found)
Checking for SSA/ASS support                                      : yes
Checking for libass OSD support                                   : yes
Checking for dummy OSD support                                    : libass-osd found
Checking for zlib                                                 : yes
Checking for Encoding                                             : yes
Checking for Bluray support                                       : yes
Checking for dvdread support                                      : disabled
Checking for dvdnav support                                       : disabled
Checking for DVD/IFO support                                      : not found any of dvdnav, dvdread
Checking for cdda support (libcdio)                               : disabled
Checking for uchardet support                                     : no ('uchardet' not found)
Checking for librubberband support                                : no ('rubberband >= 1.8.0' not found)
Checking for LCMS2 support                                        : no ('lcms2 >= 2.6' not found)
Checking for VapourSynth filter bridge (Python)                   : no ('vapoursynth >= 24 vapoursynth-script >= 23' not found)
Checking for VapourSynth filter bridge (Lazy Lua)                 : no ('vapoursynth >= 24' not found)
Checking for VapourSynth filter bridge (core)                     : not found any of vapoursynth-lazy, vapoursynth
Checking for libarchive wrapper for reading zip files and more    : disabled
Checking for SDL2                                                 : disabled
Checking for SDL (1.x)                                            : disabled
Checking for OSS                                                  : yes
Checking for RSound audio output                                  : no
Checking for sndio audio input/output                             : disabled
Checking for PulseAudio audio output                              : yes
Checking for JACK audio output                                    : no ('jack' not found)
Checking for OpenAL audio output                                  : disabled
Checking for OpenSL ES audio output                               : no
Checking for ALSA audio output                                    : no ('alsa >= 1.0.18' not found)
Checking for CoreAudio audio output                               : no
Checking for AudioUnit output for iOS                             : no
Checking for WASAPI audio output                                  : not found any of os-win32, os-cygwin
Checking for Cocoa                                                : no
Checking for DRM                                                  : yes
Checking for GBM                                                  : gbm.h not found
Checking for Wayland                                              : no ('wayland-client >= 1.6.0 wayland-cursor >= 1.6.0 xkbcommon >= 0.3.0' not found)
Checking for X11                                                  : no ('x11 >= 1.0.0 xscrnsaver >= 1.0.0 xext >= 1.0.0 xinerama >= 1.0.0 xrandr >= 1.2.0' not found)
Checking for Xv video output                                      : x11 not found
Checking for OpenGL Cocoa Backend                                 : cocoa not found
Checking for OpenGL X11 Backend                                   : x11 not found
Checking for OpenGL X11 EGL Backend                               : x11 not found
Checking for OpenGL DRM EGL Backend                               : gbm not found
Checking for OpenGL Wayland Backend                               : wayland not found
Checking for OpenGL Win32 Backend                                 : win32-desktop not found
Checking for OpenGL/DirectX Interop Backend                       : gl-win32 not found
Checking for OpenGL ANGLE headers                                 : not found any of os-win32, os-cygwin
Checking for OpenGL Win32 ANGLE Library                           : egl-angle not found
Checking for OpenGL Win32 ANGLE Backend                           : win32-desktop, egl-angle not found
Checking for VDPAU acceleration                                   : x11 not found
Checking for VDPAU with OpenGL/X11                                : vdpau, gl-x11 not found
Checking for VAAPI acceleration                                   : not found any of wayland, egl-drm, x11
Checking for VAAPI (X11 support)                                  : vaapi, x11 not found
Checking for VAAPI (Wayland support)                              : vaapi, gl-wayland not found
Checking for VAAPI (DRM/EGL support)                              : vaapi, egl-drm not found
Checking for VAAPI GLX                                            : vaapi-x11, gl-x11 not found
Checking for VAAPI EGL on X11                                     : vaapi-x11, egl-x11 not found
Checking for VAAPI EGL                                            : not found any of vaapi-wayland, vaapi-x-egl
Checking for CACA                                                 : yes
Checking for JPEG support                                         : yes
Checking for Direct3D support                                     : win32-desktop not found
Checking for Android support                                      : no
Checking for Raspberry Pi support                                 : yes
Checking for iOS OpenGL ES hardware decoding interop support      : no
Checking for OpenGL without platform-specific code (e.g. for libmpv) : not found any of libmpv-static, libmpv-shared
Checking for MALI via Linux fbdev                                    : no
Checking for OpenGL video outputs                                    : yes
Checking for EGL helper functions                                    : yes
Checking for FFmpeg/Libav present                                    : yes
Checking for libav* is FFmpeg                                        : no
Checking for libav* is Libav                                         : no
Checking for Libav/FFmpeg library versions                           : not found any of is_ffmpeg, is_libav
Unable to find development files for some of the required FFmpeg/Libav libraries. You need at least FFmpeg 3.2.2 or Libav 12. Aborting.
`

**Comment by kevmitch** [comment]
Works here. Could you post `mpv-build/mpv/build/config.log`?

**Comment by geezuh** [comment]
http://termbin.com/wyi9

**Comment by sfan5** [comment]
<pre>
['/usr/bin/cc', '-pthread', '-pthread', 'test.c.1.o', '-o/home/pi/src/mpv-build/mpv/build/.conf_check_299f26f0aade5fb398ff77c8d9fc8f06/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/home/pi/src/mpv-build/build_libs/lib', '-lavcodec', '-lm', '-lmmal_core', '-lmmal_util', '-lmmal_vc_client', '-lbcm_host', '-lz', '-lswresample', '-lm', '-lavutil', '-lm']
err: /usr/bin/ld: cannot find -lmmal_core
/usr/bin/ld: cannot find -lmmal_util
/usr/bin/ld: cannot find -lmmal_vc_client
/usr/bin/ld: cannot find -lbcm_host
collect2: error: ld returned 1 exit status
</pre>
it's trying to link the the RPi's gpu bullshit libraries, you need `-L/opt/vc/lib` or similar in your ldflags

**Comment by geezuh** [comment]
Hey! I got it to build! Thanks for pointing me in the right direction.
In case anyone else is having this same issue, I had to set both of the following env variables before running ./rebuild

export CPATH="/opt/vc/include"
export LDFLAGS="-L/opt/vc/lib"

**Comment by CZyMfnIPC** [comment]
@geezuh Hey there! I am also trying to build on a raspberry pi, but I am having troubles even with the export flags.

Which directions did you follow? And what OS are you running?
Thanks!
