### ISSUE TITLE
Include libressl fix with ffmpeg

### ISSUE THREAD

**Issue by onodera-punpun** [mpv-player/mpv-build#99]
By default ffmpeg doesn't compile when using libressl, this patch fixes that: https://github.com/gentoo/libressl/blob/master/media-video/ffmpeg/files/ffmpeg-3.3-libressl.patch

It would be nice if this gets applied.

**Comment by kevmitch** [comment]
I think you need to talk to ffmpeg about this. The `mpv-build` scripts are currently undergoing an overhaul that will allow you to specify post update hooks (in which you could apply this patch yourself), but I don't think that we want to deal with applying patches by default.
